document.addEventListener('DOMContentLoaded', () => {
  const yearEls = document.querySelectorAll('#year');
  yearEls.forEach((el) => {
    el.textContent = new Date().getFullYear();
  });

  const translations = {
    en: {
      navHome: 'Home',
      navRecipes: 'Recipes',
      navCategories: 'Categories',
      navAbout: 'About',
      navContact: 'Contact',
      navServices: 'Services',
      navProjects: 'Projects',
      homeEyebrow: 'Fresh ideas for the kitchen',
      homeTitle: 'Cook meals that feel cozy, bright, and effortless.',
      homeText: 'Discover quick dinners, comforting classics, and seasonal favorites with simple steps and bold flavor.',
      homeCta: 'Explore Recipes',
      badgeQuick: '30-minute meals',
      badgeWeeknight: 'Weeknight favorites',
      badgeHealthy: 'Healthy swaps',
      recipeOfDayLabel: 'Recipe of the day',
      recipeOfDayText: 'Finding a fresh dish for today.',
      recipeOfDayButton: 'See this recipe',
      recipeOfTheDayImageAlt: 'Recipe of the day',
      loadingText: 'Loading...',
      navToggleAria: 'Toggle navigation',
      languageSwitcherAria: 'Choose language',
      themeToggleAria: 'Toggle color theme',
      statRecipes: 'Recipes shared',
      statRating: 'Average rating',
      statPrep: 'Fastest prep',
      statFriendly: 'Home-cook friendly',
      popularEyebrow: 'Popular this week',
      popularTitle: 'Make something delicious tonight.',
      cardSoupTitle: 'Smoky Tomato Soup',
      cardSoupText: 'Rich, cozy, and ready in under 25 minutes with a toasted cheese finish.',
      cardSoupButton: 'View Recipe',
      cardSalmonTitle: 'Maple Glazed Salmon',
      cardSalmonText: 'Bright, balanced, and perfect for a quick dinner with roasted vegetables.',
      cardSalmonButton: 'View Recipe',
      cardParfaitTitle: 'Honey Yogurt Parfait',
      cardParfaitText: 'A layered sweet-and-tangy breakfast that feels both simple and indulgent.',
      cardParfaitButton: 'View Recipe',
      cardWrapTitle: 'Crispy Chickpea Wrap',
      cardWrapText: 'Crunchy roasted chickpeas, greens, and a creamy drizzle make a quick lunch you’ll repeat.',
      cardWrapButton: 'View Recipe',
      quickRecipe01Ing1: 'Salmon fillets',
      quickRecipe01Ing2: 'Butter, garlic, lemon',
      quickRecipe01Ing3: 'Parsley and black pepper',
      quickRecipe01Step1: 'Season salmon and pan-sear until lightly crisp.',
      quickRecipe01Step2: 'Cook garlic in butter, then add lemon juice and parsley.',
      quickRecipe01Step3: 'Spoon the sauce over the fish and serve with greens.',
      quickRecipe02Ing1: 'Cheese tortellini',
      quickRecipe02Ing2: 'Cooked chicken, pesto, cherry tomatoes',
      quickRecipe02Ing3: 'Parmesan and basil',
      quickRecipe02Step1: 'Boil the tortellini until tender, then drain.',
      quickRecipe02Step2: 'Warm chicken with pesto and tomatoes until glossy.',
      quickRecipe02Step3: 'Toss everything together and finish with parmesan.',
      quickRecipe03Ing1: 'Cooked rice',
      quickRecipe03Ing2: 'Chicken, black beans, corn',
      quickRecipe03Ing3: 'Avocado, salsa, cheese',
      quickRecipe03Step1: 'Season chicken and cook until browned.',
      quickRecipe03Step2: 'Layer rice, beans, corn, and avocado in bowls.',
      quickRecipe03Step3: 'Top with chicken, salsa, cheese, and lime.',
      quickRecipe04Ing1: 'Rice noodles',
      quickRecipe04Ing2: 'Tofu, snap peas, carrots',
      quickRecipe04Ing3: 'Miso paste, soy sauce, sesame oil',
      quickRecipe04Step1: 'Cook noodles and set aside.',
      quickRecipe04Step2: 'Pan-fry tofu and vegetables until lightly charred.',
      quickRecipe04Step3: 'Stir in miso sauce and toss with noodles.',
      quickRecipe05Ing1: 'Flatbread',
      quickRecipe05Ing2: 'Tomatoes, olives, feta',
      quickRecipe05Ing3: 'Olive oil, oregano, garlic',
      quickRecipe05Step1: 'Brush the flatbread with olive oil and garlic.',
      quickRecipe05Step2: 'Top with tomatoes, olives, and feta.',
      quickRecipe05Step3: 'Bake until crisp at the edges and serve warm.',
      quickRecipe06Title: 'Honey Soy Chicken Skillet',
      quickRecipe06Text: 'Tender chicken and vegetables glazed with a sweet-savory sauce.',
      quickRecipe06Ing1: 'Chicken breast',
      quickRecipe06Ing2: 'Broccoli, carrots, bell pepper',
      quickRecipe06Ing3: 'Honey, soy sauce, ginger',
      quickRecipe06Step1: 'Cook chicken until golden and caramelized.',
      quickRecipe06Step2: 'Add vegetables and sauté until crisp-tender.',
      quickRecipe06Step3: 'Pour in honey-soy sauce and glaze everything well.',
      quickRecipe07Title: 'Spinach Ricotta Toasts',
      quickRecipe07Text: 'Toasted bread topped with creamy ricotta and wilted greens.',
      quickRecipe07Ing1: 'Sourdough or baguette',
      quickRecipe07Ing2: 'Ricotta, spinach, garlic',
      quickRecipe07Ing3: 'Lemon zest and chili flakes',
      quickRecipe07Step1: 'Toast bread until crisp.',
      quickRecipe07Step2: 'Cook spinach with garlic until wilted.',
      quickRecipe07Step3: 'Spread ricotta, add spinach, and finish with lemon zest.',
      quickRecipe08Title: 'Smoky Tomato Pasta',
      quickRecipe08Text: 'A pantry-friendly pasta with roasted tomatoes and a silky finish.',
      quickRecipe08Ing1: 'Pasta',
      quickRecipe08Ing2: 'Tomatoes, garlic, chili flakes',
      quickRecipe08Ing3: 'Olive oil and parmesan',
      quickRecipe08Step1: 'Cook pasta and reserve a little cooking water.',
      quickRecipe08Step2: 'Simmer garlic and tomatoes until saucy and fragrant.',
      quickRecipe08Step3: 'Toss with pasta, parmesan, and chili flakes.',
      quickRecipe09Title: 'Lemon Herb Shrimp',
      quickRecipe09Text: 'Juicy shrimp in a bright lemon pan sauce that feels dinner-party worthy.',
      quickRecipe09Ing1: 'Shrimp',
      quickRecipe09Ing2: 'Garlic, butter, lemon',
      quickRecipe09Ing3: 'Parsley and capers',
      quickRecipe09Step1: 'Cook shrimp quickly in a hot skillet.',
      quickRecipe09Step2: 'Add butter, garlic, lemon, and capers.',
      quickRecipe09Step3: 'Finish with parsley and serve immediately.',
      quickRecipe10Title: 'Cheesy Broccoli Quesadillas',
      quickRecipe10Text: 'Crisp tortillas filled with broccoli, cheese, and a little spice.',
      quickRecipe10Ing1: 'Tortillas',
      quickRecipe10Ing2: 'Broccoli, cheddar, onion',
      quickRecipe10Ing3: 'Greek yogurt and chili flakes',
      quickRecipe10Step1: 'Sauté broccoli and onion until tender.',
      quickRecipe10Step2: 'Fill tortillas with cheese and vegetables.',
      quickRecipe10Step3: 'Toast until crisp and serve with yogurt.',
      recipeSectionDessertEyebrow: 'Desserts',
      recipeSectionDessertTitle: 'Sweet endings for every day',
      healthyRecipe01Title: 'Mediterranean Chickpea Salad',
      healthyRecipe01Text: 'Chickpeas, cucumbers, olives, and feta create a filling lunch bowl.',
      healthyRecipe01Ing1: 'Chickpeas',
      healthyRecipe01Ing2: 'Cucumber, tomato, olives',
      healthyRecipe01Ing3: 'Lemon dressing, feta',
      healthyRecipe01Step1: 'Combine chickpeas with chopped vegetables.',
      healthyRecipe01Step2: 'Whisk lemon juice, oil, and mustard for dressing.',
      healthyRecipe01Step3: 'Top with feta and serve chilled or room temp.',
      healthyRecipe02Title: 'Green Protein Smoothie Bowl',
      healthyRecipe02Text: 'A creamy blend of spinach, yogurt, banana, and berries for a fresh breakfast.',
      healthyRecipe02Ing1: 'Spinach',
      healthyRecipe02Ing2: 'Banana, yogurt, berries',
      healthyRecipe02Ing3: 'Chia seeds and granola',
      healthyRecipe02Step1: 'Blend spinach, banana, and yogurt until smooth.',
      healthyRecipe02Step2: 'Pour into a bowl and top with berries.',
      healthyRecipe02Step3: 'Finish with chia seeds and granola.',
      healthyRecipe03Title: 'Avocado Quinoa Bowl',
      healthyRecipe03Text: 'Quinoa, avocado, and roasted vegetables make a nourishing midday meal.',
      healthyRecipe03Ing1: 'Quinoa',
      healthyRecipe03Ing2: 'Avocado, cucumber, tomato',
      healthyRecipe03Ing3: 'Lemon dressing and herbs',
      healthyRecipe03Step1: 'Cook quinoa and cool slightly.',
      healthyRecipe03Step2: 'Layer with vegetables and avocado.',
      healthyRecipe03Step3: 'Finish with lemon dressing and herbs.',
      healthyRecipe04Title: 'Lentil Herb Soup',
      healthyRecipe04Text: 'Easy lentils, herbs, and vegetables simmer into a comforting bowl.',
      healthyRecipe04Ing1: 'Red lentils',
      healthyRecipe04Ing2: 'Carrot, celery, onion',
      healthyRecipe04Ing3: 'Vegetable stock and herbs',
      healthyRecipe04Step1: 'Sauté onion, carrot, and celery.',
      healthyRecipe04Step2: 'Add lentils and stock and simmer until soft.',
      healthyRecipe04Step3: 'Blend partly and finish with herbs.',
      healthyRecipe05Title: 'Roasted Veggie Wrap',
      healthyRecipe05Text: 'Crunchy vegetables and hummus tucked into a bright wrap for a light lunch.',
      healthyRecipe05Ing1: 'Wraps',
      healthyRecipe05Ing2: 'Roasted zucchini, peppers, onions',
      healthyRecipe05Ing3: 'Hummus and greens',
      healthyRecipe05Step1: 'Roast vegetables until tender and lightly charred.',
      healthyRecipe05Step2: 'Spread hummus over the wrap.',
      healthyRecipe05Step3: 'Layer vegetables and greens, roll tight, and slice.',
      healthyRecipe06Title: 'Citrus Kale Salad',
      healthyRecipe06Text: 'A crisp salad with citrus, seeds, and a lemony dressing.',
      healthyRecipe06Ing1: 'Kale',
      healthyRecipe06Ing2: 'Orange, avocado, pumpkin seeds',
      healthyRecipe06Ing3: 'Lemon dressing',
      healthyRecipe06Step1: 'Toss kale with citrus segments and avocado.',
      healthyRecipe06Step2: 'Sprinkle with pumpkin seeds.',
      healthyRecipe06Step3: 'Drizzle with lemon dressing and serve.',
      healthyRecipe07Title: 'Herbed Yogurt Bowl',
      healthyRecipe07Text: 'A cool yogurt bowl with cucumbers, herbs, and toasted seeds.',
      healthyRecipe07Ing1: 'Greek yogurt',
      healthyRecipe07Ing2: 'Cucumber, dill, mint',
      healthyRecipe07Ing3: 'Toasted seeds and olive oil',
      healthyRecipe07Step1: 'Season yogurt with herbs and olive oil.',
      healthyRecipe07Step2: 'Top with cucumbers and toasted seeds.',
      healthyRecipe07Step3: 'Serve cold as a light lunch or snack.',
      healthyRecipe08Title: 'Stuffed Bell Peppers',
      healthyRecipe08Text: 'Colorful peppers packed with grains, beans, and herbs.',
      healthyRecipe08Ing1: 'Bell peppers',
      healthyRecipe08Ing2: 'Rice, black beans, onion',
      healthyRecipe08Ing3: 'Tomato sauce and herbs',
      healthyRecipe08Step1: 'Fill halved peppers with the rice and bean mixture.',
      healthyRecipe08Step2: 'Place in a baking dish with tomato sauce.',
      healthyRecipe08Step3: 'Bake until the peppers are tender and the filling is hot.',
      healthyRecipe09Title: 'Warm Farro Salad',
      healthyRecipe09Text: 'Toasty farro with greens, roasted squash, and a zesty vinaigrette.',
      healthyRecipe09Ing1: 'Farro',
      healthyRecipe09Ing2: 'Roasted squash, spinach, pumpkin seeds',
      healthyRecipe09Ing3: 'Olive oil and lemon',
      healthyRecipe09Step1: 'Cook farro until tender and chewy.',
      healthyRecipe09Step2: 'Roast squash until caramelized.',
      healthyRecipe09Step3: 'Toss everything with lemon dressing and seeds.',
      healthyRecipe10Title: 'Coconut Rice Bowl',
      healthyRecipe10Text: 'A fragrant bowl of rice, vegetables, and a light coconut finish.',
      healthyRecipe10Ing1: 'Rice',
      healthyRecipe10Ing2: 'Carrot, peas, edamame',
      healthyRecipe10Ing3: 'Coconut milk and herbs',
      healthyRecipe10Step1: 'Cook rice and simmer with coconut milk.',
      healthyRecipe10Step2: 'Steam vegetables until bright and crisp-tender.',
      healthyRecipe10Step3: 'Top with herbs and serve warm.',
      dessertRecipe01Title: 'Chocolate Lava Mug Cake',
      dessertRecipe01Text: 'Warm, gooey chocolate cake made in minutes for a cozy treat.',
      dessertRecipe01Ing1: 'Flour, cocoa, sugar',
      dessertRecipe01Ing2: 'Milk, butter, egg',
      dessertRecipe01Ing3: 'Chocolate chips',
      dessertRecipe01Step1: 'Mix the dry ingredients in a mug.',
      dessertRecipe01Step2: 'Stir in the wet ingredients and chocolate chips.',
      dessertRecipe01Step3: 'Microwave until set but still soft in the center.',
      dessertRecipe02Title: 'Lemon Berry Tartlets',
      dessertRecipe02Text: 'Light pastry shells filled with cream and topped with bright berries.',
      dessertRecipe02Ing1: 'Mini pastry shells',
      dessertRecipe02Ing2: 'Cream cheese, lemon zest',
      dessertRecipe02Ing3: 'Fresh berries',
      dessertRecipe02Step1: 'Whip cream cheese with lemon zest and sugar.',
      dessertRecipe02Step2: 'Spoon into shells and top with berries.',
      dessertRecipe02Step3: 'Chill for a light, fresh finish.',
      dessertRecipe03Title: 'Vanilla Rice Pudding',
      dessertRecipe03Text: 'Soft, creamy rice pudding finished with cinnamon and vanilla.',
      dessertRecipe03Ing1: 'Rice',
      dessertRecipe03Ing2: 'Milk, sugar, vanilla',
      dessertRecipe03Ing3: 'Cinnamon and raisins',
      dessertRecipe03Step1: 'Simmer rice in milk until creamy.',
      dessertRecipe03Step2: 'Stir in sugar, vanilla, and cinnamon.',
      dessertRecipe03Step3: 'Serve warm or chilled with raisins.',
      dessertRecipe04Title: 'Berry Oat Crumble',
      dessertRecipe04Text: 'Warm fruit under a buttery oat topping that feels homemade and easy.',
      dessertRecipe04Ing1: 'Mixed berries',
      dessertRecipe04Ing2: 'Rolled oats, butter, flour',
      dessertRecipe04Ing3: 'Brown sugar and vanilla',
      dessertRecipe04Step1: 'Spread fruit in a dish and sprinkle with sugar.',
      dessertRecipe04Step2: 'Rub together oats, flour, butter, and sugar.',
      dessertRecipe04Step3: 'Bake until bubbling and golden.',
      dessertRecipe05Title: 'Panna Cotta Cups',
      dessertRecipe05Text: 'Silky vanilla custard served with fresh fruit and a little syrup.',
      dessertRecipe05Ing1: 'Heavy cream, milk',
      dessertRecipe05Ing2: 'Gelatin, sugar, vanilla',
      dessertRecipe05Ing3: 'Berry compote',
      dessertRecipe05Step1: 'Heat cream and milk with sugar and vanilla.',
      dessertRecipe05Step2: 'Stir in gelatin and pour into cups.',
      dessertRecipe05Step3: 'Chill until set and top with berries.',
      dessertRecipe06Title: 'Mini Lemon Bars',
      dessertRecipe06Text: 'Bright citrus bars with a buttery crust and a soft filling.',
      dessertRecipe06Ing1: 'Butter, flour, sugar',
      dessertRecipe06Ing2: 'Lemons, eggs',
      dessertRecipe06Ing3: 'Icing sugar',
      dessertRecipe06Step1: 'Bake a shortbread crust until lightly golden.',
      dessertRecipe06Step2: 'Pour over lemon filling and return to the oven.',
      dessertRecipe06Step3: 'Cool and dust with icing sugar.',
      dessertRecipe07Title: 'Honey Yogurt Parfait',
      dessertRecipe07Text: 'Layered yogurt, fruit, nuts, and honey for a quick sweet bite.',
      dessertRecipe07Ing1: 'Greek yogurt',
      dessertRecipe07Ing2: 'Berries, honey, granola',
      dessertRecipe07Ing3: 'Chopped nuts',
      dessertRecipe07Step1: 'Layer yogurt with berries and granola.',
      dessertRecipe07Step2: 'Drizzle with honey and add nuts.',
      dessertRecipe07Step3: 'Serve chilled for a quick dessert.',
      dessertRecipe08Title: 'Chocolate Banana Pops',
      dessertRecipe08Text: 'Frozen banana pops coated in chocolate and sprinkled with crunch.',
      dessertRecipe08Ing1: 'Bananas',
      dessertRecipe08Ing2: 'Dark chocolate, coconut flakes',
      dessertRecipe08Ing3: 'Sprinkles or nuts',
      dessertRecipe08Step1: 'Insert sticks into halved bananas.',
      dessertRecipe08Step2: 'Dip in melted chocolate and add toppings.',
      dessertRecipe08Step3: 'Freeze until firm before serving.',
      dessertRecipe09Title: 'Cinnamon Apple Crisp',
      dessertRecipe09Text: 'Tender apples baked under a spice-scented crisp topping.',
      dessertRecipe09Ing1: 'Apples',
      dessertRecipe09Ing2: 'Brown sugar, oats, butter',
      dessertRecipe09Ing3: 'Cinnamon and vanilla',
      dessertRecipe09Step1: 'Slice apples and toss with sugar and cinnamon.',
      dessertRecipe09Step2: 'Top with oats, butter, and brown sugar.',
      dessertRecipe09Step3: 'Bake until bubbling and golden.',
      dessertRecipe10Title: 'Almond Berry Tart',
      dessertRecipe10Text: 'A simple almond crust filled with cream and fresh berries.',
      dessertRecipe10Ing1: 'Almond flour',
      dessertRecipe10Ing2: 'Butter, sugar, cream cheese',
      dessertRecipe10Ing3: 'Fresh berries',
      dessertRecipe10Step1: 'Press almond crust into a tart pan and bake.',
      dessertRecipe10Step2: 'Fill with sweetened cream cheese.',
      dessertRecipe10Step3: 'Top with berries and chill before serving.',
      footerCategories: 'Categories',
      cardRisottoTitle: 'Creamy Mushroom Risotto',
      cardRisottoText: 'Silky rice, earthy mushrooms, and parmesan create a cozy dinner that feels restaurant-worthy.',
      cardRisottoButton: 'View Recipe',
      cardCrumbleTitle: 'Berry Oat Crumble',
      cardCrumbleText: 'Warm berries, oat topping, and a spoonful of vanilla make the perfect finish to any meal.',
      cardCrumbleButton: 'View Recipe',
      whyEyebrow: 'Why cooks love us',
      whyTitle: 'Beautiful recipes, practical directions, and comforting flavor.',
      whyText: 'Kitchenlo brings together approachable meals, seasonal planning, and easy-to-follow steps that keep cooking fun.',
      whyButton: 'Learn More',
      previewOneTitle: 'Quick weeknight dinners',
      previewOneText: 'Every recipe is designed to save time without sacrificing taste.',
      previewTwoTitle: 'Flexible ingredient swaps',
      previewTwoText: 'Use what you have at home and still get a satisfying result.',
      dailyRecipeOneTitle: 'Golden Herb Pasta',
      dailyRecipeOneText: 'Silky noodles, roasted garlic, and crunchy herbs create a dinner that comes together fast.',
      dailyRecipeOneAlt: 'A bowl of golden herb pasta with fresh parsley',
      dailyRecipeTwoTitle: 'Citrus Garden Salad',
      dailyRecipeTwoText: 'Bright greens, roasted citrus, and creamy feta bring a light yet satisfying lunch to the table.',
      dailyRecipeTwoAlt: 'A fresh citrus salad with herbs and vegetables',
      dailyRecipeThreeTitle: 'Honey Roasted Chicken',
      dailyRecipeThreeText: 'A cozy plate with caramelized edges, warm spices, and a glossy glaze that feels homemade.',
      dailyRecipeThreeAlt: 'Honey roasted chicken served with herbs',
      footerRights: 'All rights reserved.',
      footerRecipes: 'Recipes',
      footerContact: 'Contact',
      aboutEyebrow: 'About Kitchenlo',
      aboutTitle: 'We make home cooking feel inspired, practical, and joyful.',
      aboutIntro: 'Kitchenlo is a recipe destination built for busy people who still want meals full of warmth and personality.',
      aboutHeading: 'Built for real kitchens.',
      aboutParaOne: 'From weeknight dinners to cozy weekend bakes, our recipes are created to work in real homes with real schedules. We focus on flavor, simplicity, and flexible ingredients.',
      aboutParaTwo: 'Whether you need a quick lunch, a nourishing dinner, or a crowd-pleasing dessert, Kitchenlo is here to help you cook with confidence.',
      aboutListTitle: 'What you’ll find',
      aboutListOne: 'Easy meal ideas for any day',
      aboutListTwo: 'Clear steps and pantry-friendly tips',
      aboutListThree: 'Recipes that balance comfort and freshness',
      recipePageEyebrow: 'Recipe collection',
      recipePageTitle: 'Handpicked dishes for comfort, speed, and everyday joy.',
      recipePageIntro: 'Browse favorites that are simple to follow and satisfying to share.',
      recipeSectionQuickEyebrow: 'Quick favorites',
      recipeSectionQuickTitle: '30-minute meals',
      recipeSectionWeeknightEyebrow: 'Cozy and reliable',
      recipeSectionWeeknightTitle: 'Weeknight favorites',
      recipeSectionHealthyEyebrow: 'Better-for-you plates',
      recipeSectionHealthyTitle: 'Healthy swaps',
      recipeFlatbreadTitle: 'Roasted Veggie Flatbread',
      recipeFlatbreadText: 'Layered with herbed cream cheese, roasted vegetables, and a crisp finish.',
      recipeIngredientsLabel: 'Ingredients:',
      recipeMethodLabel: 'Method:',
      recipeFlatbreadIngredientOne: 'Flatbread',
      recipeFlatbreadIngredientTwo: 'Herbed cream cheese',
      recipeFlatbreadIngredientThree: 'Roasted peppers, zucchini, onion',
      recipeFlatbreadMethod: 'Spread the cream cheese, layer the vegetables, then bake until crisp and golden.',
      recipeNoodleTitle: 'Sesame Noodle Bowl',
      recipeNoodleText: 'A speedy noodle dish with crunchy vegetables and a nutty sauce.',
      recipeNoodleIngredientOne: 'Rice noodles',
      recipeNoodleIngredientTwo: 'Carrot, cucumber, scallions',
      recipeNoodleIngredientThree: 'Sesame oil, soy sauce, lime',
      recipeNoodleMethod: 'Toss the cooked noodles with vegetables and sauce until glossy and bright.',
      recipeTacoTitle: 'Spicy Shrimp Tacos',
      recipeTacoText: 'Bright, bold, and packed with texture in just minutes.',
      recipeTacoIngredientOne: 'Shrimp',
      recipeTacoIngredientTwo: 'Small tortillas',
      recipeTacoIngredientThree: 'Avocado, slaw, hot sauce',
      recipeTacoMethod: 'Sear the shrimp, pile into warm tortillas, and top with crisp slaw.',
      recipeChickenTitle: 'One-Pan Lemon Chicken',
      recipeChickenText: 'Bright citrus, garlic, and baby potatoes make this dinner feel special with minimal cleanup.',
      recipeChickenIngredientOne: 'Chicken thighs',
      recipeChickenIngredientTwo: 'Lemons and garlic',
      recipeChickenIngredientThree: 'Baby potatoes and olive oil',
      recipeChickenMethod: 'Roast everything together until the chicken is golden and the potatoes are tender.',
      recipeMeatballsTitle: 'Herbed Turkey Meatballs',
      recipeMeatballsText: 'Comforting and flavorful, perfect for a steady dinner with pasta or rice.',
      recipeMeatballsIngredientOne: 'Ground turkey',
      recipeMeatballsIngredientTwo: 'Parsley, garlic, breadcrumbs',
      recipeMeatballsIngredientThree: 'Tomato sauce',
      recipeMeatballsMethod: 'Mix, roll into meatballs, and simmer in sauce until fully cooked.',
      recipeTacoDinnerTitle: 'Breakfast-for-Dinner Tacos',
      recipeTacoDinnerText: 'Scrambled eggs, avocado, and salsa make an easy crowd-pleaser.',
      recipeTacoDinnerIngredientOne: 'Eggs',
      recipeTacoDinnerIngredientTwo: 'Avocado and salsa',
      recipeTacoDinnerIngredientThree: 'Warm tortillas',
      recipeTacoDinnerMethod: 'Scramble the eggs, fill the tortillas, and top with avocado and salsa.',
      recipeRiceTitle: 'Spiced Coconut Rice',
      recipeRiceText: 'Warm, fragrant, and the perfect side for a lighter grain bowl.',
      recipeRiceIngredientOne: 'Rice',
      recipeRiceIngredientTwo: 'Coconut milk',
      recipeRiceIngredientThree: 'Cumin, turmeric, salt',
      recipeRiceMethod: 'Simmer the rice in coconut milk with spices until fluffy and fragrant.',
      recipeQuinoaTitle: 'Avocado Quinoa Bowl',
      recipeQuinoaText: 'Protein-rich, fresh, and easy to prep ahead for lunches.',
      recipeQuinoaIngredientOne: 'Quinoa',
      recipeQuinoaIngredientTwo: 'Avocado, cucumber, tomato',
      recipeQuinoaIngredientThree: 'Lemon dressing',
      recipeQuinoaMethod: 'Layer the cooked quinoa with vegetables and finish with a lemony dressing.',
      recipeWrapTitle: 'Roasted Veggie Wrap',
      recipeWrapText: 'Crunchy vegetables and herby sauce make this a satisfying swap for heavier meals.',
      recipeWrapIngredientOne: 'Wraps',
      recipeWrapIngredientTwo: 'Roasted vegetables',
      recipeWrapIngredientThree: 'Hummus and herbs',
      recipeWrapMethod: 'Fill the wrap with roasted vegetables and hummus, then roll tightly.',
      guideEyebrow: 'Complete guide',
      guideTitle: 'Roasted Veggie Flatbread from start to finish',
      guideIntro: 'This recipe is simple, colorful, and perfect for sharing. Follow these steps from prep to serving.',
      guideStepOneTitle: '1. Prep the vegetables',
      guideStepOneText: 'Roast sliced peppers, zucchini, and onion with olive oil, salt, and a little oregano until lightly golden.',
      guideStepTwoTitle: '2. Spread the base',
      guideStepTwoText: 'Lay the flatbread on a tray and smooth on a generous layer of herbed cream cheese.',
      guideStepThreeTitle: '3. Build the topping',
      guideStepThreeText: 'Scatter the roasted vegetables over the base and finish with a few fresh herbs.',
      guideStepFourTitle: '4. Bake and serve',
      guideStepFourText: 'Bake until the edges are crisp, slice into pieces, and serve warm with a light salad.',
      categoryEyebrow: 'Browse by category',
      categoryTitle: 'Find recipes that match your mood, time, and cravings.',
      categoryIntro: 'Choose from quick dinners, comforting classics, fresh bowls, and sweet treats.',
      categoryQuickTitle: 'Quick Dinners',
      categoryQuickText: 'Fast meals with minimal prep and maximum flavor.',
      categoryQuickButton: 'See recipes',
      categoryDessertTitle: 'Desserts',
      categoryDessertText: 'Sweet finishes for cozy evenings and easy celebrations.',
      categoryDessertButton: 'See recipes',
      projectsEyebrow: 'Browse by category',
      projectsTitle: 'Find recipes that match your mood, time, and cravings.',
      projectsIntro: 'Choose from quick dinners, comforting classics, fresh bowls, and sweet treats.',
      projectsQuickTitle: 'Quick Dinners',
      projectsQuickText: 'Fast meals with minimal prep and maximum flavor.',
      projectsBreakfastTitle: 'Breakfast',
      projectsBreakfastText: 'Warm pastries, brunch plates, and energizing bowls.',
      projectsDessertTitle: 'Desserts',
      projectsDessertText: 'Soft bakes, chilled treats, and simple sweets.',
      servicesEyebrow: 'Services',
      servicesTitle: 'Flexible support for founders, creatives, and growing businesses.',
      servicesIntro: 'Choose a package that fits your stage and goals, whether you need a fresh launch or a full redesign.',
      serviceLaunchTitle: 'Launch Site',
      serviceLaunchPrice: 'From $1,200',
      serviceLaunchItemOne: 'Custom one-page launch site',
      serviceLaunchItemTwo: 'Modern visuals and layout',
      serviceLaunchItemThree: 'Fast delivery and mobile-ready',
      serviceGrowthTitle: 'Growth Website',
      serviceGrowthPrice: 'From $2,500',
      serviceGrowthItemOne: 'Multi-page website structure',
      serviceGrowthItemTwo: 'SEO foundations',
      serviceGrowthItemThree: 'CMS-friendly content setup',
      servicePremiumTitle: 'Premium Redesign',
      servicePremiumPrice: 'From $4,000',
      servicePremiumItemOne: 'Full visual refresh',
      servicePremiumItemTwo: 'UX improvements and messaging',
      servicePremiumItemThree: 'Ongoing optimization support',
      quickCategoryItem01: 'Garlic Butter Salmon',
      quickCategoryItem02: 'Pesto Chicken Tortellini',
      quickCategoryItem03: 'Crispy Taco Rice Bowls',
      quickCategoryItem04: 'Miso Noodle Stir-Fry',
      quickCategoryItem05: 'Mediterranean Flatbread',
      quickCategoryItem06: 'Honey Soy Chicken Skillet',
      quickCategoryItem07: 'Spinach Ricotta Toasts',
      quickCategoryItem08: 'Smoky Tomato Pasta',
      quickCategoryItem09: 'Lemon Herb Shrimp',
      quickCategoryItem10: 'Cheesy Broccoli Quesadillas',
      healthyCategoryItem01: 'Mediterranean Chickpea Salad',
      healthyCategoryItem02: 'Green Protein Smoothie Bowl',
      healthyCategoryItem03: 'Avocado Quinoa Bowl',
      healthyCategoryItem04: 'Lentil Herb Soup',
      healthyCategoryItem05: 'Roasted Veggie Wrap',
      healthyCategoryItem06: 'Citrus Kale Salad',
      healthyCategoryItem07: 'Herbed Yogurt Bowl',
      healthyCategoryItem08: 'Stuffed Bell Peppers',
      healthyCategoryItem09: 'Warm Farro Salad',
      healthyCategoryItem10: 'Coconut Rice Bowl',
      dessertCategoryItem01: 'Chocolate Lava Mug Cake',
      dessertCategoryItem02: 'Lemon Berry Tartlets',
      dessertCategoryItem03: 'Vanilla Rice Pudding',
      dessertCategoryItem04: 'Berry Oat Crumble',
      dessertCategoryItem05: 'Panna Cotta Cups',
      dessertCategoryItem06: 'Mini Lemon Bars',
      dessertCategoryItem07: 'Honey Yogurt Parfait',
      dessertCategoryItem08: 'Chocolate Banana Pops',
      dessertCategoryItem09: 'Cinnamon Apple Crisp',
      dessertCategoryItem10: 'Almond Berry Tart',
      viewRecipe: 'View Recipe',
      contactEyebrow: 'Contact us',
      contactTitle: 'Share your favorite recipe idea or ask for inspiration.',
      contactIntro: 'We’d love to hear what you’re cooking and what you want to see next.',
      contactNameLabel: 'Name',
      contactNamePlaceholder: 'Your name',
      contactEmailLabel: 'Email',
      contactEmailPlaceholder: 'you@example.com',
      contactTopicLabel: 'Topic',
      contactOptionRecipe: 'Recipe request',
      contactOptionTip: 'Cooking tip',
      contactOptionSwap: 'Ingredient swap',
      contactOptionFeedback: 'General feedback',
      contactMessageLabel: 'Message',
      contactMessagePlaceholder: 'Tell us what you’d like to cook or learn',
      contactSubmit: 'Send Message',
      contactInfoTitle: 'Visit the kitchen',
      contactInfoEmail: 'Email: hello@kitchenlo.com',
      contactInfoInspiration: 'Inspiration: Daily recipe updates',
      contactInfoResponse: 'Response: Usually within one business day'
    },
    fr: {
      navHome: 'Accueil',
      navRecipes: 'Recettes',
      navCategories: 'Catégories',
      navAbout: 'À propos',
      navContact: 'Contact',
      navServices: 'Services',
      navProjects: 'Projets',
      homeEyebrow: 'Des idées fraîches pour la cuisine',
      homeTitle: 'Préparez des repas chaleureusement lumineux et sans effort.',
      homeText: 'Découvrez des dîners rapides, des classiques réconfortants et des favoris de saison avec des étapes simples et des saveurs marquées.',
      homeCta: 'Explorer les recettes',
      badgeQuick: 'Repas en 30 minutes',
      badgeWeeknight: 'Favoris de soir',
      badgeHealthy: 'Échanges sains',
      recipeOfDayLabel: 'Recette du jour',
      recipeOfDayText: 'Nous avons trouvé un plat frais pour aujourd’hui.',
      recipeOfDayButton: 'Voir cette recette',
      recipeOfTheDayImageAlt: 'Recette du jour',
      loadingText: 'Chargement...',
      navToggleAria: 'Basculer la navigation',
      languageSwitcherAria: 'Choisir la langue',
      themeToggleAria: 'Basculer le thème de couleur',
      statRecipes: 'Recettes partagées',
      statRating: 'Note moyenne',
      statPrep: 'Préparation la plus rapide',
      statFriendly: 'Adapté aux cuisiniers à la maison',
      popularEyebrow: 'Populaire cette semaine',
      popularTitle: 'Faites quelque chose de délicieux ce soir.',
      cardSoupTitle: 'Soupe de tomate fumée',
      cardSoupText: 'Riche, réconfortante et prête en moins de 25 minutes avec une finition de fromage toasté.',
      cardSoupButton: 'Voir la recette',
      cardSalmonTitle: 'Saumon glacé au sirop d’érable',
      cardSalmonText: 'Éclatant, équilibré et parfait pour un dîner rapide avec des légumes rôtis.',
      cardSalmonButton: 'Voir la recette',
      cardParfaitTitle: 'Parfait au yaourt miel',
      cardParfaitText: 'Un petit-déjeuner superposé, doux et acidulé, à la fois simple et gourmand.',
      cardParfaitButton: 'Voir la recette',
      whyEyebrow: 'Pourquoi les cuisiniers nous aiment',
      whyTitle: 'De belles recettes, des instructions pratiques et une saveur réconfortante.',
      whyText: 'Kitchenlo rassemble des repas accessibles, une planification saisonnière et des étapes faciles à suivre pour garder la cuisine ludique.',
      whyButton: 'En savoir plus',
      previewOneTitle: 'Dîners rapides de semaine',
      previewOneText: 'Chaque recette est pensée pour gagner du temps sans sacrifier le goût.',
      previewTwoTitle: 'Échanges d’ingrédients flexibles',
      previewTwoText: 'Utilisez ce que vous avez à la maison et obtenez quand même un résultat satisfaisant.',
      dailyRecipeOneTitle: 'Pâtes dorées aux herbes',
      dailyRecipeOneText: 'Des nouilles soyeuses, de l’ail rôti et des herbes croustillantes créent un dîner rapide à préparer.',
      dailyRecipeOneAlt: 'Un bol de pâtes dorées aux herbes avec du persil frais',
      dailyRecipeTwoTitle: 'Salade de jardin aux agrumes',
      dailyRecipeTwoText: 'Des légumes verts éclatants, des agrumes rôtis et de la feta crémeuse apportent un déjeuner léger et satisfaisant.',
      dailyRecipeTwoAlt: 'Une salade fraîche aux agrumes avec des herbes et des légumes',
      dailyRecipeThreeTitle: 'Poulet rôti au miel',
      dailyRecipeThreeText: 'Une assiette chaleureuse avec des bords caramélisés, des épices douillettes et une glaze brillante qui semble faite maison.',
      dailyRecipeThreeAlt: 'Poulet rôti au miel servi avec des herbes',
      footerRights: 'Tous droits réservés.',
      footerRecipes: 'Recettes',
      footerContact: 'Contact',
      aboutEyebrow: 'À propos de Kitchenlo',
      aboutTitle: 'Nous rendons la cuisine à la maison inspirante, pratique et joyeuse.',
      aboutIntro: 'Kitchenlo est une destination de recettes conçue pour les personnes occupées qui veulent néanmoins des repas pleins de chaleur et de personnalité.',
      aboutHeading: 'Conçu pour de vraies cuisines.',
      aboutParaOne: 'Des dîners de semaine aux gâteaux de fin de semaine, nos recettes sont conçues pour fonctionner dans de vraies maisons et avec de vrais horaires.',
      aboutParaTwo: 'Que vous ayez besoin d’un rapide déjeuner, d’un dîner nourrissant ou d’un dessert qui plaît à tous, Kitchenlo est là pour vous aider à cuisiner en toute confiance.',
      aboutListTitle: 'Ce que vous trouverez',
      aboutListOne: 'Des idées de repas faciles pour chaque jour',
      aboutListTwo: 'Des étapes claires et des astuces pratiques',
      aboutListThree: 'Des recettes qui équilibrent confort et fraîcheur',
      recipePageEyebrow: 'Collection de recettes',
      recipePageTitle: 'Des plats choisis pour le confort, la rapidité et la joie quotidienne.',
      recipePageIntro: 'Parcourez des favoris simples à suivre et agréables à partager.',
      recipeSectionQuickEyebrow: 'Favoris rapides',
      recipeSectionQuickTitle: 'Repas en 30 minutes',
      recipeSectionWeeknightEyebrow: 'Confort et fiabilité',
      recipeSectionWeeknightTitle: 'Favoris de soirée',
      recipeSectionHealthyEyebrow: 'Plats plus sains',
      recipeSectionHealthyTitle: 'Échanges sains',
      recipeFlatbreadTitle: 'Pain plat aux légumes rôtis',
      recipeFlatbreadText: 'Composé de fromage à la crème aux herbes, de légumes rôtis et d’une finition croustillante.',
      quickRecipe01Ing1: 'Filets de saumon',
      quickRecipe01Ing2: 'Beurre, ail, citron',
      quickRecipe01Ing3: 'Persil et poivre noir',
      quickRecipe01Step1: 'Assaisonnez le saumon et faites-le saisir à la poêle jusqu’à ce qu’il soit légèrement croustillant.',
      quickRecipe01Step2: 'Faites fondre l’ail dans le beurre puis ajoutez le jus de citron et le persil.',
      quickRecipe01Step3: 'Versez la sauce sur le poisson et servez avec des légumes verts.',
      quickRecipe02Ing1: 'Tortellini au fromage',
      quickRecipe02Ing2: 'Poulet cuit, pesto, tomates cerises',
      quickRecipe02Ing3: 'Parmesan et basilic',
      quickRecipe02Step1: 'Faites bouillir les tortellini jusqu’à ce qu’ils soient tendres, puis égouttez-les.',
      quickRecipe02Step2: 'Chauffez le poulet avec le pesto et les tomates jusqu’à ce que la sauce soit brillante.',
      quickRecipe02Step3: 'Mélangez le tout et terminez avec du parmesan.',
      quickRecipe03Ing1: 'Riz cuit',
      quickRecipe03Ing2: 'Poulet, haricots noirs, maïs',
      quickRecipe03Ing3: 'Avocat, salsa, fromage',
      quickRecipe03Step1: 'Assaisonnez le poulet et faites-le cuire jusqu’à ce qu’il soit doré.',
      quickRecipe03Step2: 'Disposez le riz, les haricots, le maïs et l’avocat dans les bols.',
      quickRecipe03Step3: 'Ajoutez le poulet, la salsa, le fromage et le citron vert.',
      quickRecipe04Ing1: 'Nouilles de riz',
      quickRecipe04Ing2: 'Tofu, pois mangetout, carottes',
      quickRecipe04Ing3: 'Pâte miso, sauce soja, huile de sésame',
      quickRecipe04Step1: 'Faites cuire les nouilles puis réservez-les.',
      quickRecipe04Step2: 'Faites revenir le tofu et les légumes jusqu’à ce qu’ils soient légèrement grillés.',
      quickRecipe04Step3: 'Ajoutez la sauce au miso et mélangez avec les nouilles.',
      quickRecipe05Ing1: 'Pain plat',
      quickRecipe05Ing2: 'Tomates, olives, feta',
      quickRecipe05Ing3: 'Huile d’olive, origan, ail',
      quickRecipe05Step1: 'Badigeonnez le pain plat avec de l’huile d’olive et de l’ail.',
      quickRecipe05Step2: 'Ajoutez tomates, olives et feta.',
      quickRecipe05Step3: 'Faites cuire jusqu’à ce que les bords soient croustillants et servez chaud.',
      quickRecipe06Title: 'Poêlée de poulet au soja miel',
      quickRecipe06Text: 'Poulet tendre et légumes glacés avec une sauce douce et savoureuse.',
      quickRecipe06Ing1: 'Poitrine de poulet',
      quickRecipe06Ing2: 'Brocoli, carottes, poivron',
      quickRecipe06Ing3: 'Miel, sauce soja, gingembre',
      quickRecipe06Step1: 'Faites cuire le poulet jusqu’à ce qu’il soit doré et caramélisé.',
      quickRecipe06Step2: 'Ajoutez les légumes et faites-les sauter jusqu’à ce qu’ils soient tendres-croquants.',
      quickRecipe06Step3: 'Versez la sauce miel-soja et nappez le tout.',
      quickRecipe07Title: 'Tartines de ricotta et épinards',
      quickRecipe07Text: 'Pain grillé garni de ricotta crémeuse et de légumes fondants.',
      quickRecipe07Ing1: 'Pain au levain ou baguette',
      quickRecipe07Ing2: 'Ricotta, épinards, ail',
      quickRecipe07Ing3: 'Zeste de citron et flocons de piment',
      quickRecipe07Step1: 'Grillez le pain jusqu’à ce qu’il soit croustillant.',
      quickRecipe07Step2: 'Faites fondre les épinards avec l’ail.',
      quickRecipe07Step3: 'Étalez la ricotta, ajoutez les épinards et terminez avec du zeste de citron.',
      quickRecipe08Title: 'Pâtes tomate fumée',
      quickRecipe08Text: 'Des pâtes faciles avec des tomates rôties et une finition délicate.',
      quickRecipe08Ing1: 'Pâtes',
      quickRecipe08Ing2: 'Tomates, ail, flocons de piment',
      quickRecipe08Ing3: 'Huile d’olive et parmesan',
      quickRecipe08Step1: 'Faites cuire les pâtes et réservez un peu d’eau de cuisson.',
      quickRecipe08Step2: 'Faites mijoter ail et tomates jusqu’à obtenir une sauce parfumée.',
      quickRecipe08Step3: 'Mélangez avec les pâtes, le parmesan et les flocons de piment.',
      quickRecipe09Title: 'Crevettes au citron et aux herbes',
      quickRecipe09Text: 'Crevettes juteuses dans une sauce au citron éclatante qui a la classe d’un dîner festif.',
      quickRecipe09Ing1: 'Crevettes',
      quickRecipe09Ing2: 'Ail, beurre, citron',
      quickRecipe09Ing3: 'Persil et câpres',
      quickRecipe09Step1: 'Faites cuire les crevettes rapidement dans une poêle chaude.',
      quickRecipe09Step2: 'Ajoutez beurre, ail, citron et câpres.',
      quickRecipe09Step3: 'Terminez avec du persil et servez immédiatement.',
      quickRecipe10Title: 'Quesadillas de brocoli au fromage',
      quickRecipe10Text: 'Tortillas croustillantes remplies de brocoli, fromage et un peu d’épice.',
      quickRecipe10Ing1: 'Tortillas',
      quickRecipe10Ing2: 'Brocoli, cheddar, oignon',
      quickRecipe10Ing3: 'Yaourt grec et flocons de piment',
      quickRecipe10Step1: 'Faites revenir le brocoli et l’oignon jusqu’à ce qu’ils soient tendres.',
      quickRecipe10Step2: 'Remplissez les tortillas avec le fromage et les légumes.',
      quickRecipe10Step3: 'Grillez jusqu’à ce qu’elles soient croustillantes et servez avec du yaourt.',
      recipeSectionDessertEyebrow: 'Desserts',
      recipeSectionDessertTitle: 'Fins sucrées pour chaque jour',
      healthyRecipe01Title: 'Salade de pois chiches méditerranéenne',
      healthyRecipe01Text: 'Pois chiches, concombres, olives et feta créent un bol de déjeuner copieux.',
      healthyRecipe01Ing1: 'Pois chiches',
      healthyRecipe01Ing2: 'Concombre, tomate, olives',
      healthyRecipe01Ing3: 'Vinaigrette au citron, feta',
      healthyRecipe01Step1: 'Mélangez les pois chiches avec les légumes hachés.',
      healthyRecipe01Step2: 'Fouettez le jus de citron, l’huile et la moutarde pour la vinaigrette.',
      healthyRecipe01Step3: 'Ajoutez la feta et servez bien froid ou à température ambiante.',
      healthyRecipe02Title: 'Bol de smoothie vert protéiné',
      healthyRecipe02Text: 'Un mélange crémeux d’épinards, de yaourt, de banane et de baies pour un petit-déjeuner frais.',
      healthyRecipe02Ing1: 'Épinards',
      healthyRecipe02Ing2: 'Banane, yaourt, baies',
      healthyRecipe02Ing3: 'Graines de chia et granola',
      healthyRecipe02Step1: 'Mixez les épinards, la banane et le yaourt jusqu’à obtenir une texture lisse.',
      healthyRecipe02Step2: 'Versez dans un bol et ajoutez les baies.',
      healthyRecipe02Step3: 'Terminez avec des graines de chia et de la granola.',
      healthyRecipe03Title: 'Bol de quinoa à l’avocat',
      healthyRecipe03Text: 'Quinoa, avocat et légumes rôtis pour un repas du midi nourrissant.',
      healthyRecipe03Ing1: 'Quinoa',
      healthyRecipe03Ing2: 'Avocat, concombre, tomate',
      healthyRecipe03Ing3: 'Vinaigrette au citron et herbes',
      healthyRecipe03Step1: 'Faites cuire le quinoa et laissez-le tiédir légèrement.',
      healthyRecipe03Step2: 'Disposez-le avec les légumes et l’avocat.',
      healthyRecipe03Step3: 'Terminez avec la vinaigrette au citron et les herbes.',
      healthyRecipe04Title: 'Soupe de lentilles aux herbes',
      healthyRecipe04Text: 'Des lentilles faciles, des herbes et des légumes mijotent dans un bol réconfortant.',
      healthyRecipe04Ing1: 'Lentilles rouges',
      healthyRecipe04Ing2: 'Carotte, céleri, oignon',
      healthyRecipe04Ing3: 'Bouillon végétal et herbes',
      healthyRecipe04Step1: 'Faites revenir l’oignon, la carotte et le céleri.',
      healthyRecipe04Step2: 'Ajoutez les lentilles et le bouillon et laissez mijoter jusqu’à ce qu’elles soient tendres.',
      healthyRecipe04Step3: 'Mixez partiellement et terminez avec les herbes.',
      healthyRecipe05Title: 'Wrap de légumes rôtis',
      healthyRecipe05Text: 'Des légumes croustillants et du houmous enveloppés dans un wrap lumineux pour un déjeuner léger.',
      healthyRecipe05Ing1: 'Wraps',
      healthyRecipe05Ing2: 'Courgettes, poivrons, oignons rôtis',
      healthyRecipe05Ing3: 'Houmous et légumes verts',
      healthyRecipe05Step1: 'Rôti les légumes jusqu’à ce qu’ils soient tendres et légèrement grillés.',
      healthyRecipe05Step2: 'Étalez le houmous sur le wrap.',
      healthyRecipe05Step3: 'Ajoutez légumes et verdure, roule bien et découpe.',
      healthyRecipe06Title: 'Salade de chou frisé aux agrumes',
      healthyRecipe06Text: 'Une salade croquante avec des agrumes, des graines et une vinaigrette citronnée.',
      healthyRecipe06Ing1: 'Chou frisé',
      healthyRecipe06Ing2: 'Orange, avocat, graines de courge',
      healthyRecipe06Ing3: 'Vinaigrette au citron',
      healthyRecipe06Step1: 'Mélangez le chou frisé avec les segments d’agrumes et l’avocat.',
      healthyRecipe06Step2: 'Ajoutez les graines de courge.',
      healthyRecipe06Step3: 'Versez la vinaigrette au citron et servez.',
      healthyRecipe07Title: 'Bol de yaourt aux herbes',
      healthyRecipe07Text: 'Un bol de yaourt frais avec concombre, herbes et graines toastées.',
      healthyRecipe07Ing1: 'Yaourt grec',
      healthyRecipe07Ing2: 'Concombre, aneth, menthe',
      healthyRecipe07Ing3: 'Graines grillées et huile d’olive',
      healthyRecipe07Step1: 'Assaisonnez le yaourt avec les herbes et l’huile d’olive.',
      healthyRecipe07Step2: 'Ajoutez le concombre et les graines grillées.',
      healthyRecipe07Step3: 'Servez froid comme déjeuner léger ou en-cas.',
      healthyRecipe08Title: 'Poivrons farcis',
      healthyRecipe08Text: 'Des poivrons colorés remplis de grains, de haricots et d’herbes.',
      healthyRecipe08Ing1: 'Poivrons',
      healthyRecipe08Ing2: 'Riz, haricots noirs, oignon',
      healthyRecipe08Ing3: 'Sauce tomate et herbes',
      healthyRecipe08Step1: 'Remplissez les demi-poivrons avec le mélange de riz et de haricots.',
      healthyRecipe08Step2: 'Placez-les dans un plat avec la sauce tomate.',
      healthyRecipe08Step3: 'Faites cuire jusqu’à ce que les poivrons soient tendres et le farce bien chaud.',
      healthyRecipe09Title: 'Salade chaude de farro',
      healthyRecipe09Text: 'Farro toasté avec des légumes verts, une courge rôtie et une vinaigrette zeste.',
      healthyRecipe09Ing1: 'Farro',
      healthyRecipe09Ing2: 'Courge rôtie, épinards, graines de courge',
      healthyRecipe09Ing3: 'Huile d’olive et citron',
      healthyRecipe09Step1: 'Faites cuire le farro jusqu’à ce qu’il soit tendre et moelleux.',
      healthyRecipe09Step2: 'Rôtissez la courge jusqu’à ce qu’elle soit caramélisée.',
      healthyRecipe09Step3: 'Mélangez le tout avec la vinaigrette citronnée et les graines.',
      healthyRecipe10Title: 'Bol de riz au coco',
      healthyRecipe10Text: 'Un bol parfumé de riz, de légumes et d’une légère touche de coco.',
      healthyRecipe10Ing1: 'Riz',
      healthyRecipe10Ing2: 'Carotte, pois, edamame',
      healthyRecipe10Ing3: 'Lait de coco et herbes',
      healthyRecipe10Step1: 'Faites cuire le riz et laissez-le mijoter avec le lait de coco.',
      healthyRecipe10Step2: 'Faites cuire les légumes jusqu’à ce qu’ils restent lumineux et tendres.',
      healthyRecipe10Step3: 'Ajoutez les herbes et servez chaud.',
      dessertRecipe01Title: 'Gâteau au chocolat en mug',
      dessertRecipe01Text: 'Un gâteau au chocolat chaud et fondant en quelques minutes pour une petite douceur cocooning.',
      dessertRecipe01Ing1: 'Farine, cacao, sucre',
      dessertRecipe01Ing2: 'Lait, beurre, œuf',
      dessertRecipe01Ing3: 'Pépites de chocolat',
      dessertRecipe01Step1: 'Mélangez les ingrédients secs dans un mug.',
      dessertRecipe01Step2: 'Ajoutez les ingrédients humides et les morceaux de chocolat.',
      dessertRecipe01Step3: 'Mettez au micro-ondes jusqu’à ce que le gâteau soit pris mais encore moelleux au centre.',
      dessertRecipe02Title: 'Tartelettes aux baies et citron',
      dessertRecipe02Text: 'Coquilles légères de pâte garnies de crème et de baies éclatantes.',
      dessertRecipe02Ing1: 'Coquilles de pâte miniatures',
      dessertRecipe02Ing2: 'Fromage à la crème, zeste de citron',
      dessertRecipe02Ing3: 'Baies fraîches',
      dessertRecipe02Step1: 'Fouettez le fromage à la crème avec le zeste de citron et le sucre.',
      dessertRecipe02Step2: 'Versez dans les coquilles et ajoutez les baies.',
      dessertRecipe02Step3: 'Laissez reposer au frais pour une finition légère et fraîche.',
      dessertRecipe03Title: 'Pudding au riz à la vanille',
      dessertRecipe03Text: 'Un pudding au riz doux et crémeux fini à la cannelle et à la vanille.',
      dessertRecipe03Ing1: 'Riz',
      dessertRecipe03Ing2: 'Lait, sucre, vanille',
      dessertRecipe03Ing3: 'Cannelle et raisins',
      dessertRecipe03Step1: 'Faites mijoter le riz dans le lait jusqu’à ce qu’il soit crémeux.',
      dessertRecipe03Step2: 'Ajoutez sucre, vanille et cannelle.',
      dessertRecipe03Step3: 'Servez chaud ou froid avec des raisins.',
      dessertRecipe04Title: 'Crumble aux fruits et aux flocons d’avoine',
      dessertRecipe04Text: 'Des fruits chauds sous une pâte croustillante au beurre et aux flocons.',
      dessertRecipe04Ing1: 'Baies mélangées',
      dessertRecipe04Ing2: 'Flocons d’avoine, beurre, farine',
      dessertRecipe04Ing3: 'Sucre brun et vanille',
      dessertRecipe04Step1: 'Étalez les fruits dans un plat et saupoudrez de sucre.',
      dessertRecipe04Step2: 'Frottez ensemble les flocons d’avoine, la farine, le beurre et le sucre.',
      dessertRecipe04Step3: 'Faites cuire jusqu’à ce que le mélange bouillonne et doré.',
      dessertRecipe05Title: 'Coupes de panna cotta',
      dessertRecipe05Text: 'Crème vanillée onctueuse servie avec des fruits frais et un peu de sirop.',
      dessertRecipe05Ing1: 'Crème épaisse, lait',
      dessertRecipe05Ing2: 'Gélatine, sucre, vanille',
      dessertRecipe05Ing3: 'Compote de baies',
      dessertRecipe05Step1: 'Chauffez la crème et le lait avec le sucre et la vanille.',
      dessertRecipe05Step2: 'Ajoutez la gélatine et versez dans des coupes.',
      dessertRecipe05Step3: 'Laissez refroidir jusqu’à ce que ça prenne et ajoutez des baies.',
      dessertRecipe06Title: 'Mini barres au citron',
      dessertRecipe06Text: 'Des barres citronnées lumineuses avec une pâte beurrée et une garniture douce.',
      dessertRecipe06Ing1: 'Beurre, farine, sucre',
      dessertRecipe06Ing2: 'Citrons, œufs',
      dessertRecipe06Ing3: 'Sucre glace',
      dessertRecipe06Step1: 'Faites cuire une pâte sablée jusqu’à ce qu’elle soit légèrement dorée.',
      dessertRecipe06Step2: 'Versez la garniture au citron et remettez au four.',
      dessertRecipe06Step3: 'Laissez refroidir et saupoudrez de sucre glace.',
      dessertRecipe07Title: 'Parfait au yaourt miel',
      dessertRecipe07Text: 'Yaourt, fruits, noix et miel superposés pour une petite douceur rapide.',
      dessertRecipe07Ing1: 'Yaourt grec',
      dessertRecipe07Ing2: 'Baies, miel, granola',
      dessertRecipe07Ing3: 'Noix hachées',
      dessertRecipe07Step1: 'Superposez le yaourt avec les baies et la granola.',
      dessertRecipe07Step2: 'Ajoutez du miel et des noix.',
      dessertRecipe07Step3: 'Servez bien froid pour un dessert rapide.',
      dessertRecipe08Title: 'Sorbets banane chocolat',
      dessertRecipe08Text: 'Bananes congelées recouvertes de chocolat et de croustillant.',
      dessertRecipe08Ing1: 'Bananes',
      dessertRecipe08Ing2: 'Chocolat noir, flocons de coco',
      dessertRecipe08Ing3: 'Sprinkles ou noix',
      dessertRecipe08Step1: 'Insérez les bâtonnets dans les bananes coupées en deux.',
      dessertRecipe08Step2: 'Trempez dans le chocolat fondu et ajoutez les garnitures.',
      dessertRecipe08Step3: 'Laissez congeler jusqu’à ce qu’elles soient fermes avant de servir.',
      dessertRecipe09Title: 'Crumble pommes-cannelle',
      dessertRecipe09Text: 'Pommes tendres cuites sous une couche épicée et croustillante.',
      dessertRecipe09Ing1: 'Pommes',
      dessertRecipe09Ing2: 'Sucre brun, flocons d’avoine, beurre',
      dessertRecipe09Ing3: 'Cannelle et vanille',
      dessertRecipe09Step1: 'Coupez les pommes et mélangez-les avec le sucre et la cannelle.',
      dessertRecipe09Step2: 'Ajoutez les flocons d’avoine, le beurre et le sucre brun.',
      dessertRecipe09Step3: 'Faites cuire jusqu’à ce que le mélange bouillonne et soit doré.',
      dessertRecipe10Title: 'Tarte aux baies et amandes',
      dessertRecipe10Text: 'Une simple pâte aux amandes garnie de crème et de baies fraîches.',
      dessertRecipe10Ing1: 'Farine d’amandes',
      dessertRecipe10Ing2: 'Beurre, sucre, fromage à la crème',
      dessertRecipe10Ing3: 'Baies fraîches',
      dessertRecipe10Step1: 'Appuyez la pâte aux amandes dans un moule et faites cuire.',
      dessertRecipe10Step2: 'Garnissez avec du fromage à la crème sucré.',
      dessertRecipe10Step3: 'Ajoutez les baies et laissez refroidir avant de servir.',
      footerCategories: 'Catégories',
      recipeIngredientsLabel: 'Ingrédients :',
      recipeMethodLabel: 'Méthode :',
      recipeFlatbreadIngredientOne: 'Pain plat',
      recipeFlatbreadIngredientTwo: 'Fromage à la crème aux herbes',
      recipeFlatbreadIngredientThree: 'Poivrons, courgettes, oignon rôtis',
      recipeFlatbreadMethod: 'Étalez le fromage à la crème, disposez les légumes puis faites cuire jusqu’à ce que le tout soit croustillant et doré.',
      recipeNoodleTitle: 'Bol de nouilles au sésame',
      recipeNoodleText: 'Un plat de nouilles rapide avec des légumes croquants et une sauce noisette.',
      recipeNoodleIngredientOne: 'Nouilles de riz',
      recipeNoodleIngredientTwo: 'Carotte, concombre, oignons verts',
      recipeNoodleIngredientThree: 'Huile de sésame, sauce soja, citron vert',
      recipeNoodleMethod: 'Mélangez les nouilles cuites avec les légumes et la sauce jusqu’à ce qu’elles brillent.',
      recipeTacoTitle: 'Tacos épicés aux crevettes',
      recipeTacoText: 'Vifs, audacieux et riches en texture en quelques minutes seulement.',
      recipeTacoIngredientOne: 'Crevettes',
      recipeTacoIngredientTwo: 'Petits tortillas',
      recipeTacoIngredientThree: 'Avocat, salade, sauce piquante',
      recipeTacoMethod: 'Faites saisir les crevettes, remplissez les tortillas chaudes et terminez avec une salade croustillante.',
      recipeChickenTitle: 'Poulet citron en une seule poêle',
      recipeChickenText: 'Citron, ail et pommes de terre nouvelles rendent ce dîner spécial sans trop de nettoyage.',
      recipeChickenIngredientOne: 'Cuisses de poulet',
      recipeChickenIngredientTwo: 'Citrons et ail',
      recipeChickenIngredientThree: 'Petites pommes de terre et huile d’olive',
      recipeChickenMethod: 'Faites rôtir le tout ensemble jusqu’à ce que le poulet soit doré et les pommes de terre tendres.',
      recipeMeatballsTitle: 'Boulettes dinde aux herbes',
      recipeMeatballsText: 'Confortantes et savoureuses, parfaites pour un dîner avec des pâtes ou du riz.',
      recipeMeatballsIngredientOne: 'Dinde hachée',
      recipeMeatballsIngredientTwo: 'Persil, ail, chapelure',
      recipeMeatballsIngredientThree: 'Sauce tomate',
      recipeMeatballsMethod: 'Mélangez, roulez en boulettes et laissez mijoter dans la sauce jusqu’à cuisson complète.',
      recipeTacoDinnerTitle: 'Tacos petit-déjeuner pour le dîner',
      recipeTacoDinnerText: 'Œufs brouillés, avocat et salsa font un repas convivial et facile.',
      recipeTacoDinnerIngredientOne: 'Œufs',
      recipeTacoDinnerIngredientTwo: 'Avocat et salsa',
      recipeTacoDinnerIngredientThree: 'Tortillas chaudes',
      recipeTacoDinnerMethod: 'Brouillez les œufs, remplissez les tortillas et garnissez d’avocat et de salsa.',
      recipeRiceTitle: 'Riz au lait de coco épicé',
      recipeRiceText: 'Chaud, parfumé et parfait comme accompagnement d’un bol plus léger.',
      recipeRiceIngredientOne: 'Riz',
      recipeRiceIngredientTwo: 'Lait de coco',
      recipeRiceIngredientThree: 'Cumin, curcuma, sel',
      recipeRiceMethod: 'Faites cuire le riz dans le lait de coco avec les épices jusqu’à ce qu’il soit moelleux et parfumé.',
      recipeQuinoaTitle: 'Bol de quinoa à l’avocat',
      recipeQuinoaText: 'Riche en protéines, frais et facile à préparer à l’avance pour les déjeuners.',
      recipeQuinoaIngredientOne: 'Quinoa',
      recipeQuinoaIngredientTwo: 'Avocat, concombre, tomate',
      recipeQuinoaIngredientThree: 'Vinaigrette au citron',
      recipeQuinoaMethod: 'Disposez le quinoa cuit avec les légumes et terminez avec une vinaigrette citronnée.',
      recipeWrapTitle: 'Wrap de légumes rôtis',
      recipeWrapText: 'Des légumes croustillants et une sauce aux herbes pour un substitut satisfaisant aux repas plus lourds.',
      recipeWrapIngredientOne: 'Wraps',
      recipeWrapIngredientTwo: 'Légumes rôtis',
      recipeWrapIngredientThree: 'Houmous et herbes',
      recipeWrapMethod: 'Remplissez le wrap avec les légumes rôtis et le houmous, puis roulez bien.',
      guideEyebrow: 'Guide complet',
      guideTitle: 'Pain plat aux légumes rôtis du début à la fin',
      guideIntro: 'Cette recette est simple, colorée et parfaite à partager. Suivez ces étapes de la préparation au service.',
      guideStepOneTitle: '1. Préparer les légumes',
      guideStepOneText: 'Rôtissez poivrons, courgettes et oignon avec de l’huile d’olive, du sel et un peu d’origan jusqu’à ce qu’ils soient légèrement dorés.',
      guideStepTwoTitle: '2. Étaler la base',
      guideStepTwoText: 'Posez le pain plat sur une plaque et étalez une couche généreuse de fromage à la crème aux herbes.',
      guideStepThreeTitle: '3. Construire le dessus',
      guideStepThreeText: 'Répartissez les légumes rôtis sur la base et terminez avec quelques herbes fraîches.',
      guideStepFourTitle: '4. Cuire et servir',
      guideStepFourText: 'Faites cuire jusqu’à ce que les bords soient croustillants, découpez en morceaux et servez chaud avec une salade légère.',
      categoryEyebrow: 'Parcourir par catégorie',
      categoryTitle: 'Trouvez des recettes qui correspondent à votre humeur, votre temps et vos envies.',
      categoryIntro: 'Choisissez parmi des dîners rapides, des classiques réconfortants, des bols frais et des douceurs.',
      categoryQuickTitle: 'Dîners rapides',
      categoryQuickText: 'Des repas rapides avec peu de préparation et beaucoup de goût.',
      categoryQuickButton: 'Voir les recettes',
      categoryDessertTitle: 'Desserts',
      categoryDessertText: 'Des fins sucrées pour les soirées cocooning et les célébrations faciles.',
      categoryDessertButton: 'Voir les recettes',
      projectsEyebrow: 'Parcourir par catégorie',
      projectsTitle: 'Trouvez des recettes qui correspondent à votre humeur, votre temps et vos envies.',
      projectsIntro: 'Choisissez parmi des dîners rapides, des classiques réconfortants, des bols frais et des douceurs.',
      projectsQuickTitle: 'Dîners rapides',
      projectsQuickText: 'Des repas rapides avec peu de préparation et beaucoup de goût.',
      projectsBreakfastTitle: 'Petit-déjeuner',
      projectsBreakfastText: 'Pâtisseries chaudes, plats de brunch et bols énergétiques.',
      projectsDessertTitle: 'Desserts',
      projectsDessertText: 'Gâteaux doux, friandises froides et douceurs simples.',
      servicesEyebrow: 'Services',
      servicesTitle: 'Un soutien flexible pour les fondateurs, les créatifs et les entreprises en croissance.',
      servicesIntro: 'Choisissez un forfait adapté à votre étape et à vos objectifs, que vous ayez besoin d’un lancement ou d’une refonte complète.',
      serviceLaunchTitle: 'Site de lancement',
      serviceLaunchPrice: 'À partir de 1 200 €',
      serviceLaunchItemOne: 'Site de lancement sur une page',
      serviceLaunchItemTwo: 'Visuels modernes et mise en page',
      serviceLaunchItemThree: 'Livraison rapide et compatible mobile',
      serviceGrowthTitle: 'Site de croissance',
      serviceGrowthPrice: 'À partir de 2 500 €',
      serviceGrowthItemOne: 'Structure de site multi-pages',
      serviceGrowthItemTwo: 'Fondations SEO',
      serviceGrowthItemThree: 'Mise en place du contenu compatible CMS',
      servicePremiumTitle: 'Refonte premium',
      servicePremiumPrice: 'À partir de 4 000 €',
      servicePremiumItemOne: 'Refonte visuelle complète',
      servicePremiumItemTwo: 'Améliorations UX et message',
      servicePremiumItemThree: 'Support d’optimisation continu',
      quickCategoryItem01: 'Saumon au beurre d’ail',
      quickCategoryItem02: 'Tortellini au poulet pesto',
      quickCategoryItem03: 'Bol de riz taco croustillant',
      quickCategoryItem04: 'Sauté de nouilles au miso',
      quickCategoryItem05: 'Pain plat méditerranéen',
      quickCategoryItem06: 'Poêlée de poulet au soja miel',
      quickCategoryItem07: 'Tartines de ricotta et épinards',
      quickCategoryItem08: 'Pâtes tomate fumée',
      quickCategoryItem09: 'Crevettes au citron et aux herbes',
      quickCategoryItem10: 'Quesadillas de brocoli au fromage',
      healthyCategoryItem01: 'Salade de pois chiches méditerranéenne',
      healthyCategoryItem02: 'Bol de smoothie vert protéiné',
      healthyCategoryItem03: 'Bol de quinoa à l’avocat',
      healthyCategoryItem04: 'Soupe de lentilles aux herbes',
      healthyCategoryItem05: 'Wrap de légumes rôtis',
      healthyCategoryItem06: 'Salade de chou frisé au citron',
      healthyCategoryItem07: 'Bol de yaourt aux herbes',
      healthyCategoryItem08: 'Poivrons farcis',
      healthyCategoryItem09: 'Salade chaude de farro',
      healthyCategoryItem10: 'Bol de riz au coco',
      dessertCategoryItem01: 'Gâteau au chocolat en mug',
      dessertCategoryItem02: 'Tartelettes aux baies et citron',
      dessertCategoryItem03: 'Pudding au riz à la vanille',
      dessertCategoryItem04: 'Crumble aux fruits et aux flocons d’avoine',
      dessertCategoryItem05: 'Cups de panna cotta',
      dessertCategoryItem06: 'Mini barres au citron',
      dessertCategoryItem07: 'Parfait au yaourt miel',
      dessertCategoryItem08: 'Sorbets banane chocolat',
      dessertCategoryItem09: 'Crumble pommes-cannelle',
      dessertCategoryItem10: 'Tarte aux baies et amandes',
      viewRecipe: 'Voir la recette',
      contactEyebrow: 'Contactez-nous',
      contactTitle: 'Partagez votre idée de recette préférée ou demandez de l’inspiration.',
      contactIntro: 'Nous serions ravis d’entendre ce que vous cuisinez et ce que vous souhaitez voir ensuite.',
      contactNameLabel: 'Nom',
      contactNamePlaceholder: 'Votre nom',
      contactEmailLabel: 'E-mail',
      contactEmailPlaceholder: 'vous@example.com',
      contactTopicLabel: 'Sujet',
      contactOptionRecipe: 'Demande de recette',
      contactOptionTip: 'Astuce de cuisine',
      contactOptionSwap: 'Échange d’ingrédients',
      contactOptionFeedback: 'Retour général',
      contactMessageLabel: 'Message',
      contactMessagePlaceholder: 'Dites-nous ce que vous aimeriez cuisiner ou apprendre',
      contactSubmit: 'Envoyer le message',
      contactInfoTitle: 'Visiter la cuisine',
      contactInfoEmail: 'E-mail : hello@kitchenlo.com',
      contactInfoInspiration: 'Inspiration : mises à jour quotidiennes des recettes',
      contactInfoResponse: 'Réponse : généralement en une journée ouvrée'
    },
    es: {
      navHome: 'Inicio',
      navRecipes: 'Recetas',
      navCategories: 'Categorías',
      navAbout: 'Sobre nosotros',
      navContact: 'Contacto',
      navServices: 'Servicios',
      navProjects: 'Proyectos',
      homeEyebrow: 'Ideas frescas para la cocina',
      homeTitle: 'Prepara comidas que se sientan acogedoras, luminosas y sencillas.',
      homeText: 'Descubre cenas rápidas, clásicos reconfortantes y favoritos de temporada con pasos sencillos y un sabor intenso.',
      homeCta: 'Explorar recetas',
      badgeQuick: 'Comidas en 30 minutos',
      badgeWeeknight: 'Favoritos de semana',
      badgeHealthy: 'Cambios saludables',
      recipeOfDayLabel: 'Receta del día',
      recipeOfDayText: 'Encontrando un plato fresco para hoy.',
      recipeOfDayButton: 'Ver esta receta',
      recipeOfTheDayImageAlt: 'Receta del día',
      loadingText: 'Cargando...',
      navToggleAria: 'Alternar navegación',
      languageSwitcherAria: 'Elegir idioma',
      themeToggleAria: 'Cambiar el tema de color',
      statRecipes: 'Recetas compartidas',
      statRating: 'Valoración media',
      statPrep: 'Preparación más rápida',
      statFriendly: 'Amigable para cocinar en casa',
      popularEyebrow: 'Popular esta semana',
      popularTitle: 'Haz algo delicioso esta noche.',
      cardSoupTitle: 'Sopa de tomate ahumado',
      cardSoupText: 'Rica, reconfortante y lista en menos de 25 minutos con un acabado de queso tostado.',
      cardSoupButton: 'Ver receta',
      cardSalmonTitle: 'Salmón glaseado con arce',
      cardSalmonText: 'Brillante, equilibrado y perfecto para una cena rápida con verduras asadas.',
      cardSalmonButton: 'Ver receta',
      cardParfaitTitle: 'Parfait de yogur con miel',
      cardParfaitText: 'Un desayuno en capas, dulce y ácido, a la vez simple y delicioso.',
      cardParfaitButton: 'Ver receta',
      whyEyebrow: 'Por qué a los cocineros les encanta',
      whyTitle: 'Recetas bonitas, instrucciones prácticas y un sabor reconfortante.',
      whyText: 'Kitchenlo reúne comidas accesibles, planificación estacional y pasos fáciles de seguir para que cocinar siga siendo divertido.',
      whyButton: 'Saber más',
      previewOneTitle: 'Cenas rápidas entre semana',
      previewOneText: 'Cada receta está pensada para ahorrar tiempo sin sacrificar el sabor.',
      previewTwoTitle: 'Intercambios de ingredientes flexibles',
      previewTwoText: 'Usa lo que tengas en casa y aun así consigue un resultado satisfactorio.',
      dailyRecipeOneTitle: 'Pasta dorada con hierbas',
      dailyRecipeOneText: 'Fideos sedosos, ajo asado y hierbas crujientes crean una cena rápida y deliciosa.',
      dailyRecipeOneAlt: 'Un cuenco de pasta dorada con hierbas y perejil fresco',
      dailyRecipeTwoTitle: 'Ensalada de jardín con cítricos',
      dailyRecipeTwoText: 'Verduras frescas, cítricos asados y feta cremosa aportan un almuerzo ligero pero satisfactorio.',
      dailyRecipeTwoAlt: 'Una ensalada fresca de cítricos con hierbas y verduras',
      dailyRecipeThreeTitle: 'Pollo asado con miel',
      dailyRecipeThreeText: 'Un plato acogedor con bordes caramelizados, especias cálidas y un brillo brillante que parece casero.',
      dailyRecipeThreeAlt: 'Pollo asado con miel servido con hierbas',
      footerRights: 'Todos los derechos reservados.',
      footerRecipes: 'Recetas',
      footerContact: 'Contacto',
      aboutEyebrow: 'Sobre Kitchenlo',
      aboutTitle: 'Hacemos que cocinar en casa sea inspirado, práctico y alegre.',
      aboutIntro: 'Kitchenlo es un destino de recetas pensado para personas ocupadas que aún quieren comidas llenas de calidez y personalidad.',
      aboutHeading: 'Diseñado para cocinas reales.',
      aboutParaOne: 'Desde cenas entre semana hasta bizcochos de fin de semana, nuestras recetas están creadas para funcionar en hogares reales y con horarios reales.',
      aboutParaTwo: 'Ya sea que necesites un almuerzo rápido, una cena nutritiva o un postre que encante a todos, Kitchenlo está aquí para ayudarte a cocinar con confianza.',
      aboutListTitle: 'Lo que encontrarás',
      aboutListOne: 'Ideas de comidas fáciles para cualquier día',
      aboutListTwo: 'Pasos claros y consejos prácticos',
      aboutListThree: 'Recetas que equilibran confort y frescura',
      recipePageEyebrow: 'Colección de recetas',
      recipePageTitle: 'Platos escogidos para la comodidad, la rapidez y la alegría diaria.',
      recipePageIntro: 'Explora favoritos fáciles de seguir y agradables de compartir.',
      recipeSectionQuickEyebrow: 'Favoritos rápidos',
      recipeSectionQuickTitle: 'Comidas en 30 minutos',
      recipeSectionWeeknightEyebrow: 'Confort y fiabilidad',
      recipeSectionWeeknightTitle: 'Favoritos de semana',
      recipeSectionHealthyEyebrow: 'Platos más saludables',
      recipeSectionHealthyTitle: 'Cambios saludables',
      recipeFlatbreadTitle: 'Pan plano de verduras asadas',
      recipeFlatbreadText: 'Capa de queso crema con hierbas, verduras asadas y un acabado crujiente.',
      quickRecipe01Ing1: 'Filetes de salmón',
      quickRecipe01Ing2: 'Mantequilla, ajo, limón',
      quickRecipe01Ing3: 'Perejil y pimienta negra',
      quickRecipe01Step1: 'Sazona el salmón y cocínalo en la sartén hasta que quede ligeramente crujiente.',
      quickRecipe01Step2: 'Dora el ajo en mantequilla y luego añade el jugo de limón y el perejil.',
      quickRecipe01Step3: 'Vierte la salsa sobre el pescado y sírvelo con verdes.',
      quickRecipe02Ing1: 'Tortellini de queso',
      quickRecipe02Ing2: 'Pollo cocido, pesto, tomates cherry',
      quickRecipe02Ing3: 'Parmesano y albahaca',
      quickRecipe02Step1: 'Hierve el tortellini hasta que esté tierno y luego escúrrelo.',
      quickRecipe02Step2: 'Calienta el pollo con pesto y tomates hasta que se vea brillante.',
      quickRecipe02Step3: 'Mézclalo todo y termina con parmesano.',
      quickRecipe03Ing1: 'Arroz cocido',
      quickRecipe03Ing2: 'Pollo, frijoles negros, maíz',
      quickRecipe03Ing3: 'Aguacate, salsa, queso',
      quickRecipe03Step1: 'Sazona el pollo y cocínalo hasta dorarlo.',
      quickRecipe03Step2: 'Coloca arroz, frijoles, maíz y aguacate en los cuencos.',
      quickRecipe03Step3: 'Añade pollo, salsa, queso y lima.',
      quickRecipe04Ing1: 'Fideos de arroz',
      quickRecipe04Ing2: 'Tofu, guisantes, zanahorias',
      quickRecipe04Ing3: 'Pasta de miso, salsa de soja, aceite de sésamo',
      quickRecipe04Step1: 'Cocina los fideos y resérvalos.',
      quickRecipe04Step2: 'Fríe el tofu y las verduras hasta que queden ligeramente carbonizados.',
      quickRecipe04Step3: 'Añade la salsa de miso y mézclalo con los fideos.',
      quickRecipe05Ing1: 'Pan plano',
      quickRecipe05Ing2: 'Tomates, aceitunas, feta',
      quickRecipe05Ing3: 'Aceite de oliva, orégano, ajo',
      quickRecipe05Step1: 'Pinta el pan plano con aceite de oliva y ajo.',
      quickRecipe05Step2: 'Añade tomates, aceitunas y feta.',
      quickRecipe05Step3: 'Hornea hasta que los bordes estén crujientes y sírvelo caliente.',
      quickRecipe06Title: 'Salteado de pollo con salsa de soja y miel',
      quickRecipe06Text: 'Pollo tierno y verduras glaseadas con una salsa dulce y sabrosa.',
      quickRecipe06Ing1: 'Pechuga de pollo',
      quickRecipe06Ing2: 'Brócoli, zanahorias, pimiento',
      quickRecipe06Ing3: 'Miel, salsa de soja, jengibre',
      quickRecipe06Step1: 'Cocina el pollo hasta que esté dorado y caramelizado.',
      quickRecipe06Step2: 'Añade las verduras y saltea hasta que queden tiernas y crujientes.',
      quickRecipe06Step3: 'Vierte la salsa de soja con miel y cubre todo bien.',
      quickRecipe07Title: 'Tostadas de ricotta y espinacas',
      quickRecipe07Text: 'Pan tostado con ricotta cremosa y verduras tiernas.',
      quickRecipe07Ing1: 'Pan de masa madre o baguette',
      quickRecipe07Ing2: 'Ricotta, espinacas, ajo',
      quickRecipe07Ing3: 'Ralladura de limón y chile',
      quickRecipe07Step1: 'Tuesta el pan hasta que esté crujiente.',
      quickRecipe07Step2: 'Cocina las espinacas con ajo hasta que se marchiten.',
      quickRecipe07Step3: 'Extiende la ricotta, añade espinacas y termina con ralladura de limón.',
      quickRecipe08Title: 'Pasta de tomate ahumado',
      quickRecipe08Text: 'Una pasta fácil con tomates asados y un acabado sedoso.',
      quickRecipe08Ing1: 'Pasta',
      quickRecipe08Ing2: 'Tomates, ajo, copos de chile',
      quickRecipe08Ing3: 'Aceite de oliva y parmesano',
      quickRecipe08Step1: 'Cocina la pasta y reserva un poco del agua de cocción.',
      quickRecipe08Step2: 'Cuece ajo y tomates hasta que la salsa esté fragante.',
      quickRecipe08Step3: 'Mézclalo con la pasta, parmesano y copos de chile.',
      quickRecipe09Title: 'Gambas con limón y hierbas',
      quickRecipe09Text: 'Gambas jugosas en una salsa brillante de limón que parece de cena elegante.',
      quickRecipe09Ing1: 'Gambas',
      quickRecipe09Ing2: 'Ajo, mantequilla, limón',
      quickRecipe09Ing3: 'Perejil y alcaparras',
      quickRecipe09Step1: 'Cocina las gambas rápidamente en una sartén caliente.',
      quickRecipe09Step2: 'Añade mantequilla, ajo, limón y alcaparras.',
      quickRecipe09Step3: 'Termina con perejil y sirve de inmediato.',
      quickRecipe10Title: 'Quesadillas de brócoli con queso',
      quickRecipe10Text: 'Tortillas crujientes rellenas de brócoli, queso y un toque de picante.',
      quickRecipe10Ing1: 'Tortillas',
      quickRecipe10Ing2: 'Brócoli, cheddar, cebolla',
      quickRecipe10Ing3: 'Yogur griego y copos de chile',
      quickRecipe10Step1: 'Saltea el brócoli y la cebolla hasta que estén tiernos.',
      quickRecipe10Step2: 'Rellena las tortillas con queso y verduras.',
      quickRecipe10Step3: 'Tuéstalas hasta que estén crujientes y sírvelas con yogur.',
      recipeSectionDessertEyebrow: 'Postres',
      recipeSectionDessertTitle: 'Finales dulces para cada día',
      healthyRecipe01Title: 'Ensalada mediterránea de garbanzos',
      healthyRecipe01Text: 'Garbanzos, pepinos, aceitunas y feta hacen un cuenco llenador para el almuerzo.',
      healthyRecipe01Ing1: 'Garbanzos',
      healthyRecipe01Ing2: 'Pepino, tomate, aceitunas',
      healthyRecipe01Ing3: 'Aliño de limón, feta',
      healthyRecipe01Step1: 'Combina los garbanzos con las verduras picadas.',
      healthyRecipe01Step2: 'Bate el limón, el aceite y la mostaza para el aliño.',
      healthyRecipe01Step3: 'Añade la feta y sirve fría o a temperatura ambiente.',
      healthyRecipe02Title: 'Cuenco de smoothie verde proteico',
      healthyRecipe02Text: 'Una mezcla cremosa de espinacas, yogur, plátano y bayas para un desayuno fresco.',
      healthyRecipe02Ing1: 'Espinacas',
      healthyRecipe02Ing2: 'Plátano, yogur, bayas',
      healthyRecipe02Ing3: 'Semillas de chía y granola',
      healthyRecipe02Step1: 'Bate espinacas, plátano y yogur hasta que quede suave.',
      healthyRecipe02Step2: 'Vierte en un cuenco y pon bayas encima.',
      healthyRecipe02Step3: 'Termina con semillas de chía y granola.',
      healthyRecipe03Title: 'Cuenco de quinoa con aguacate',
      healthyRecipe03Text: 'Quinoa, aguacate y verduras asadas para una comida mediodía nutritiva.',
      healthyRecipe03Ing1: 'Quinoa',
      healthyRecipe03Ing2: 'Aguacate, pepino, tomate',
      healthyRecipe03Ing3: 'Aliño de limón y hierbas',
      healthyRecipe03Step1: 'Cocina la quinoa y déjala enfriar ligeramente.',
      healthyRecipe03Step2: 'Colócala con verduras y aguacate.',
      healthyRecipe03Step3: 'Termina con el aliño de limón y hierbas.',
      healthyRecipe04Title: 'Sopa de lentejas con hierbas',
      healthyRecipe04Text: 'Lentejas fáciles, hierbas y verduras se vuelven un cuenco reconfortante.',
      healthyRecipe04Ing1: 'Lentejas rojas',
      healthyRecipe04Ing2: 'Zanahoria, apio, cebolla',
      healthyRecipe04Ing3: 'Caldo vegetal y hierbas',
      healthyRecipe04Step1: 'Saltea la cebolla, zanahoria y apio.',
      healthyRecipe04Step2: 'Añade lentejas y caldo y deja hervir hasta que estén blandas.',
      healthyRecipe04Step3: 'Muele parcialmente y termina con hierbas.',
      healthyRecipe05Title: 'Wrap de verduras asadas',
      healthyRecipe05Text: 'Verduras crujientes y hummus dentro de un wrap luminoso para un almuerzo ligero.',
      healthyRecipe05Ing1: 'Wraps',
      healthyRecipe05Ing2: 'Calabacín, pimientos, cebollas asados',
      healthyRecipe05Ing3: 'Hummus y verduras',
      healthyRecipe05Step1: 'Asa las verduras hasta que estén tiernas y ligeramente carbonizadas.',
      healthyRecipe05Step2: 'Extiende el hummus sobre el wrap.',
      healthyRecipe05Step3: 'Añade verduras y hojas, enrolla bien y corta.',
      healthyRecipe06Title: 'Ensalada de col rizada con cítricos',
      healthyRecipe06Text: 'Una ensalada crujiente con cítricos, semillas y aliño de limón.',
      healthyRecipe06Ing1: 'Col rizada',
      healthyRecipe06Ing2: 'Naranja, aguacate, semillas de calabaza',
      healthyRecipe06Ing3: 'Aliño de limón',
      healthyRecipe06Step1: 'Mezcla la col con rodajas de cítricos y aguacate.',
      healthyRecipe06Step2: 'Añade semillas de calabaza.',
      healthyRecipe06Step3: 'Rocía con aliño de limón y sirve.',
      healthyRecipe07Title: 'Cuenco de yogur con hierbas',
      healthyRecipe07Text: 'Un cuenco fresco de yogur con pepino, hierbas y semillas tostadas.',
      healthyRecipe07Ing1: 'Yogur griego',
      healthyRecipe07Ing2: 'Pepino, eneldo, menta',
      healthyRecipe07Ing3: 'Semillas tostadas y aceite de oliva',
      healthyRecipe07Step1: 'Tempera el yogur con hierbas y aceite de oliva.',
      healthyRecipe07Step2: 'Pon encima pepino y semillas tostadas.',
      healthyRecipe07Step3: 'Sírvelo frío como almuerzo ligero o tentempié.',
      healthyRecipe08Title: 'Pimientos rellenos',
      healthyRecipe08Text: 'Pimientos coloridos rellenos de granos, judías y hierbas.',
      healthyRecipe08Ing1: 'Pimientos',
      healthyRecipe08Ing2: 'Arroz, frijoles negros, cebolla',
      healthyRecipe08Ing3: 'Salsa de tomate y hierbas',
      healthyRecipe08Step1: 'Rellena los pimientos partidos por la mitad con la mezcla de arroz y judías.',
      healthyRecipe08Step2: 'Colócalos en un molde con la salsa de tomate.',
      healthyRecipe08Step3: 'Hornea hasta que los pimientos estén tiernos y el relleno caliente.',
      healthyRecipe09Title: 'Ensalada tibia de farro',
      healthyRecipe09Text: 'Farro tostado con hojas verdes, calabaza asada y vinagreta cítrica.',
      healthyRecipe09Ing1: 'Farro',
      healthyRecipe09Ing2: 'Calabaza asada, espinacas, semillas de calabaza',
      healthyRecipe09Ing3: 'Aceite de oliva y limón',
      healthyRecipe09Step1: 'Cocina el farro hasta que esté tierno y masticable.',
      healthyRecipe09Step2: 'Asa la calabaza hasta que esté caramelizada.',
      healthyRecipe09Step3: 'Mézclalo todo con aliño de limón y semillas.',
      healthyRecipe10Title: 'Cuenco de arroz con coco',
      healthyRecipe10Text: 'Un cuenco aromático de arroz, verduras y un toque ligero de coco.',
      healthyRecipe10Ing1: 'Arroz',
      healthyRecipe10Ing2: 'Zanahoria, guisantes, edamame',
      healthyRecipe10Ing3: 'Leche de coco y hierbas',
      healthyRecipe10Step1: 'Cocina el arroz y deja que hierva con la leche de coco.',
      healthyRecipe10Step2: 'Cuece las verduras hasta que queden brillantes y tiernas.',
      healthyRecipe10Step3: 'Pon hierbas encima y sirve caliente.',
      dessertRecipe01Title: 'Bizcocho de chocolate en taza',
      dessertRecipe01Text: 'Un pastel de chocolate caliente y fundente listo en minutos para un capricho cálido.',
      dessertRecipe01Ing1: 'Harina, cacao, azúcar',
      dessertRecipe01Ing2: 'Leche, mantequilla, huevo',
      dessertRecipe01Ing3: 'Chips de chocolate',
      dessertRecipe01Step1: 'Mezcla los ingredientes secos en una taza.',
      dessertRecipe01Step2: 'Añade los ingredientes húmedos y los chips de chocolate.',
      dessertRecipe01Step3: 'Microondas hasta que esté cuajado pero aún blando en el centro.',
      dessertRecipe02Title: 'Tartaletas de limón y bayas',
      dessertRecipe02Text: 'Cascarones de masa ligeros rellenos de crema y coronados con bayas brillantes.',
      dessertRecipe02Ing1: 'Caparazones de masa pequeños',
      dessertRecipe02Ing2: 'Queso crema, ralladura de limón',
      dessertRecipe02Ing3: 'Bayas frescas',
      dessertRecipe02Step1: 'Bate el queso crema con la ralladura de limón y el azúcar.',
      dessertRecipe02Step2: 'Ponlo en los caparazones y añade bayas.',
      dessertRecipe02Step3: 'Refrigera para un acabado ligero y fresco.',
      dessertRecipe03Title: 'Pudin de arroz con vainilla',
      dessertRecipe03Text: 'Un pudín de arroz suave y cremoso terminado con canela y vainilla.',
      dessertRecipe03Ing1: 'Arroz',
      dessertRecipe03Ing2: 'Leche, azúcar, vainilla',
      dessertRecipe03Ing3: 'Canela y pasas',
      dessertRecipe03Step1: 'Cuece el arroz en leche hasta que quede cremoso.',
      dessertRecipe03Step2: 'Añade azúcar, vainilla y canela.',
      dessertRecipe03Step3: 'Sírvelo caliente o frío con pasas.',
      dessertRecipe04Title: 'Crumble de bayas y avena',
      dessertRecipe04Text: 'Fruta caliente bajo una capa de avena mantequillosa que parece casera y sencilla.',
      dessertRecipe04Ing1: 'Bayas mezcladas',
      dessertRecipe04Ing2: 'Avena, mantequilla, harina',
      dessertRecipe04Ing3: 'Azúcar moreno y vainilla',
      dessertRecipe04Step1: 'Extiende la fruta en un recipiente y espolvorea azúcar.',
      dessertRecipe04Step2: 'Frota avena, harina, mantequilla y azúcar.',
      dessertRecipe04Step3: 'Hornea hasta que burbujee y quede dorado.',
      dessertRecipe05Title: 'Copas de panna cotta',
      dessertRecipe05Text: 'Natillas de vainilla sedosas servidas con fruta fresca y un poquito de sirope.',
      dessertRecipe05Ing1: 'Nata, leche',
      dessertRecipe05Ing2: 'Gelatina, azúcar, vainilla',
      dessertRecipe05Ing3: 'Compota de bayas',
      dessertRecipe05Step1: 'Calienta la nata y la leche con azúcar y vainilla.',
      dessertRecipe05Step2: 'Añade la gelatina y vierte en copas.',
      dessertRecipe05Step3: 'Enfría hasta que cuaje y pon bayas encima.',
      dessertRecipe06Title: 'Mini barras de limón',
      dessertRecipe06Text: 'Barras cítricas luminosas con una base mantequillosa y relleno suave.',
      dessertRecipe06Ing1: 'Mantequilla, harina, azúcar',
      dessertRecipe06Ing2: 'Limones, huevos',
      dessertRecipe06Ing3: 'Azúcar glas',
      dessertRecipe06Step1: 'Hornea una base sabrosa hasta que quede ligeramente dorada.',
      dessertRecipe06Step2: 'Vierte la mezcla de limón y vuelve al horno.',
      dessertRecipe06Step3: 'Enfría y espolvorea azúcar glas.',
      dessertRecipe07Title: 'Parfait de yogur con miel',
      dessertRecipe07Text: 'Yogur, fruta, nueces y miel en capas para un capricho dulce rápido.',
      dessertRecipe07Ing1: 'Yogur griego',
      dessertRecipe07Ing2: 'Bayas, miel, granola',
      dessertRecipe07Ing3: 'Nueces picadas',
      dessertRecipe07Step1: 'Coloca yogur, bayas y granola en capas.',
      dessertRecipe07Step2: 'Rocía con miel y añade nueces.',
      dessertRecipe07Step3: 'Sírvelo frío para un postre rápido.',
      dessertRecipe08Title: 'Paletas de plátano con chocolate',
      dessertRecipe08Text: 'Paletas de plátano congeladas cubiertas de chocolate con un toque crujiente.',
      dessertRecipe08Ing1: 'Plátanos',
      dessertRecipe08Ing2: 'Chocolate negro, copos de coco',
      dessertRecipe08Ing3: 'Sprinkles o nueces',
      dessertRecipe08Step1: 'Inserta palitos en los plátanos cortados por la mitad.',
      dessertRecipe08Step2: 'Sumerge en chocolate fundido y añade toppings.',
      dessertRecipe08Step3: 'Congela hasta que estén firmes antes de servir.',
      dessertRecipe09Title: 'Crumble de manzana y canela',
      dessertRecipe09Text: 'Manzanas tiernas horneadas bajo una cobertura especiada y crujiente.',
      dessertRecipe09Ing1: 'Manzanas',
      dessertRecipe09Ing2: 'Azúcar moreno, avena, mantequilla',
      dessertRecipe09Ing3: 'Canela y vainilla',
      dessertRecipe09Step1: 'Corta las manzanas y mézclalas con azúcar y canela.',
      dessertRecipe09Step2: 'Pon encima avena, mantequilla y azúcar moreno.',
      dessertRecipe09Step3: 'Hornea hasta que burbujee y quede dorado.',
      dessertRecipe10Title: 'Tarta de bayas y almendra',
      dessertRecipe10Text: 'Una base sencilla de almendra rellena de crema y bayas frescas.',
      dessertRecipe10Ing1: 'Harina de almendra',
      dessertRecipe10Ing2: 'Mantequilla, azúcar, queso crema',
      dessertRecipe10Ing3: 'Bayas frescas',
      dessertRecipe10Step1: 'Presiona la base de almendra en un molde y hornea.',
      dessertRecipe10Step2: 'Rellena con queso crema azucarado.',
      dessertRecipe10Step3: 'Pon bayas encima y refrigera antes de servir.',
      footerCategories: 'Categorías',
      recipeIngredientsLabel: 'Ingredientes:',
      recipeMethodLabel: 'Método:',
      recipeFlatbreadIngredientOne: 'Pan plano',
      recipeFlatbreadIngredientTwo: 'Queso crema con hierbas',
      recipeFlatbreadIngredientThree: 'Pimientos, calabacín y cebolla asados',
      recipeFlatbreadMethod: 'Extiende el queso crema, añade las verduras y hornea hasta que quede crujiente y dorado.',
      recipeNoodleTitle: 'Cuenco de fideos con sésamo',
      recipeNoodleText: 'Un plato rápido de fideos con verduras crujientes y una salsa sabrosa.',
      recipeNoodleIngredientOne: 'Fideos de arroz',
      recipeNoodleIngredientTwo: 'Zanahoria, pepino y cebollín',
      recipeNoodleIngredientThree: 'Aceite de sésamo, salsa de soja y lima',
      recipeNoodleMethod: 'Mezcla los fideos cocidos con las verduras y la salsa hasta que brillen.',
      recipeTacoTitle: 'Tacos picantes de gambas',
      recipeTacoText: 'Brillantes, atrevidos y llenos de textura en cuestión de minutos.',
      recipeTacoIngredientOne: 'Gambas',
      recipeTacoIngredientTwo: 'Pequeñas tortillas',
      recipeTacoIngredientThree: 'Aguacate, ensalada y salsa picante',
      recipeTacoMethod: 'Sala las gambas, rellena las tortillas calientes y termina con una ensalada crujiente.',
      recipeChickenTitle: 'Pollo con limón en una sola sartén',
      recipeChickenText: 'El limón, el ajo y las patatas pequeñas hacen que esta cena sea especial con muy poco lavado.',
      recipeChickenIngredientOne: 'Muslos de pollo',
      recipeChickenIngredientTwo: 'Limones y ajo',
      recipeChickenIngredientThree: 'Patatas pequeñas y aceite de oliva',
      recipeChickenMethod: 'Asa todo junto hasta que el pollo quede dorado y las patatas tiernas.',
      recipeMeatballsTitle: 'Albóndigas de pavo con hierbas',
      recipeMeatballsText: 'Confortables y sabrosas, perfectas para una cena con pasta o arroz.',
      recipeMeatballsIngredientOne: 'Pavo picado',
      recipeMeatballsIngredientTwo: 'Perejil, ajo y pan rallado',
      recipeMeatballsIngredientThree: 'Salsa de tomate',
      recipeMeatballsMethod: 'Mezcla, forma albóndigas y deja hervir en la salsa hasta que estén bien cocidas.',
      recipeTacoDinnerTitle: 'Tacos de desayuno para cenar',
      recipeTacoDinnerText: 'Huevos revueltos, aguacate y salsa hacen un plato fácil y popular.',
      recipeTacoDinnerIngredientOne: 'Huevos',
      recipeTacoDinnerIngredientTwo: 'Aguacate y salsa',
      recipeTacoDinnerIngredientThree: 'Tortillas calientes',
      recipeTacoDinnerMethod: 'Revuelve los huevos, rellena las tortillas y cubre con aguacate y salsa.',
      recipeRiceTitle: 'Arroz con coco especiado',
      recipeRiceText: 'Cálido, aromático y perfecto como acompañante de un cuenco más ligero.',
      recipeRiceIngredientOne: 'Arroz',
      recipeRiceIngredientTwo: 'Leche de coco',
      recipeRiceIngredientThree: 'Comino, cúrcuma y sal',
      recipeRiceMethod: 'Hierve el arroz en leche de coco con las especias hasta que quede esponjoso y aromático.',
      recipeQuinoaTitle: 'Cuenco de quinoa con aguacate',
      recipeQuinoaText: 'Rico en proteínas, fresco y fácil de preparar por adelantado para los almuerzos.',
      recipeQuinoaIngredientOne: 'Quinoa',
      recipeQuinoaIngredientTwo: 'Aguacate, pepino y tomate',
      recipeQuinoaIngredientThree: 'Aliño de limón',
      recipeQuinoaMethod: 'Coloca la quinoa cocida con las verduras y termina con un aliño cítrico.',
      recipeWrapTitle: 'Wrap de verduras asadas',
      recipeWrapText: 'Verduras crujientes y una salsa con hierbas hacen un sustituto satisfactorio para comidas más pesadas.',
      recipeWrapIngredientOne: 'Wraps',
      recipeWrapIngredientTwo: 'Verduras asadas',
      recipeWrapIngredientThree: 'Hummus y hierbas',
      recipeWrapMethod: 'Rellena el wrap con verduras asadas y hummus y luego enrolla bien.',
      guideEyebrow: 'Guía completa',
      guideTitle: 'Pan plano de verduras asadas de principio a fin',
      guideIntro: 'Esta receta es sencilla, colorida y perfecta para compartir. Sigue estos pasos desde la preparación hasta servir.',
      guideStepOneTitle: '1. Preparar las verduras',
      guideStepOneText: 'Asa pimientos, calabacín y cebolla con aceite de oliva, sal y un poco de orégano hasta que estén ligeramente dorados.',
      guideStepTwoTitle: '2. Extender la base',
      guideStepTwoText: 'Pon el pan plano sobre una bandeja y extiende una capa generosa de queso crema con hierbas.',
      guideStepThreeTitle: '3. Construir la cobertura',
      guideStepThreeText: 'Esparce las verduras asadas sobre la base y termina con algunas hierbas frescas.',
      guideStepFourTitle: '4. Hornear y servir',
      guideStepFourText: 'Hornea hasta que los bordes estén crujientes, corta en porciones y sirve caliente con una ensalada ligera.',
      categoryEyebrow: 'Explorar por categoría',
      categoryTitle: 'Encuentra recetas que encajen con tu estado de ánimo, tu tiempo y tus antojos.',
      categoryIntro: 'Elige entre cenas rápidas, clásicos reconfortantes, cuencos frescos y dulces.',
      categoryQuickTitle: 'Cenas rápidas',
      categoryQuickText: 'Comidas rápidas con poca preparación y mucho sabor.',
      categoryQuickButton: 'Ver recetas',
      categoryDessertTitle: 'Postres',
      categoryDessertText: 'Finales dulces para tardes acogedoras y celebraciones fáciles.',
      categoryDessertButton: 'Ver recetas',
      projectsEyebrow: 'Explorar por categoría',
      projectsTitle: 'Encuentra recetas que encajen con tu estado de ánimo, tu tiempo y tus antojos.',
      projectsIntro: 'Elige entre cenas rápidas, clásicos reconfortantes, cuencos frescos y dulces.',
      projectsQuickTitle: 'Cenas rápidas',
      projectsQuickText: 'Comidas rápidas con poca preparación y mucho sabor.',
      projectsBreakfastTitle: 'Desayuno',
      projectsBreakfastText: 'Pasteles calientes, platos de brunch y cuencos energizantes.',
      projectsDessertTitle: 'Postres',
      projectsDessertText: 'Pasteles suaves, dulces fríos y postres sencillos.',
      servicesEyebrow: 'Servicios',
      servicesTitle: 'Soporte flexible para fundadores, creativos y negocios en crecimiento.',
      servicesIntro: 'Elige un paquete que se adapte a tu etapa y objetivos, ya sea para un lanzamiento o un rediseño completo.',
      serviceLaunchTitle: 'Sitio de lanzamiento',
      serviceLaunchPrice: 'Desde 1.200 €',
      serviceLaunchItemOne: 'Sitio de lanzamiento de una sola página',
      serviceLaunchItemTwo: 'Visuales modernas y distribución',
      serviceLaunchItemThree: 'Entrega rápida y compatible con móviles',
      serviceGrowthTitle: 'Sitio de crecimiento',
      serviceGrowthPrice: 'Desde 2.500 €',
      serviceGrowthItemOne: 'Estructura de sitio multipágina',
      serviceGrowthItemTwo: 'Bases de SEO',
      serviceGrowthItemThree: 'Configuración de contenido compatible con CMS',
      servicePremiumTitle: 'Rediseño premium',
      servicePremiumPrice: 'Desde 4.000 €',
      servicePremiumItemOne: 'Actualización visual completa',
      servicePremiumItemTwo: 'Mejoras de UX y mensajes',
      servicePremiumItemThree: 'Soporte continuo de optimización',
      quickCategoryItem01: 'Salmón con mantequilla de ajo',
      quickCategoryItem02: 'Tortellini de pollo al pesto',
      quickCategoryItem03: 'Cuenco crujiente de arroz taco',
      quickCategoryItem04: 'Salteado de fideos con miso',
      quickCategoryItem05: 'Pan plano mediterráneo',
      quickCategoryItem06: 'Salteado de pollo con salsa de soja y miel',
      quickCategoryItem07: 'Tostadas de ricotta y espinacas',
      quickCategoryItem08: 'Pasta de tomate ahumado',
      quickCategoryItem09: 'Gambas con limón y hierbas',
      quickCategoryItem10: 'Quesadillas de brócoli con queso',
      healthyCategoryItem01: 'Ensalada mediterránea de garbanzos',
      healthyCategoryItem02: 'Cuenco de smoothie verde proteico',
      healthyCategoryItem03: 'Cuenco de quinoa con aguacate',
      healthyCategoryItem04: 'Sopa de lentejas con hierbas',
      healthyCategoryItem05: 'Wrap de verduras asadas',
      healthyCategoryItem06: 'Ensalada de col rizada con cítricos',
      healthyCategoryItem07: 'Cuenco de yogur con hierbas',
      healthyCategoryItem08: 'Pimientos rellenos',
      healthyCategoryItem09: 'Ensalada tibia de farro',
      healthyCategoryItem10: 'Cuenco de arroz con coco',
      dessertCategoryItem01: 'Bizcocho de chocolate en taza',
      dessertCategoryItem02: 'Tartaletas de limón y bayas',
      dessertCategoryItem03: 'Pudin de arroz con vainilla',
      dessertCategoryItem04: 'Crumble de bayas y avena',
      dessertCategoryItem05: 'Copas de panna cotta',
      dessertCategoryItem06: 'Mini barras de limón',
      dessertCategoryItem07: 'Parfait de yogur con miel',
      dessertCategoryItem08: 'Paletas de plátano con chocolate',
      dessertCategoryItem09: 'Crumble de manzana y canela',
      dessertCategoryItem10: 'Tarta de bayas y almendra',
      viewRecipe: 'Ver receta',
      contactEyebrow: 'Ponte en contacto',
      contactTitle: 'Comparte tu idea de receta favorita o pide inspiración.',
      contactIntro: 'Nos encantaría saber qué estás cocinando y qué te gustaría ver después.',
      contactNameLabel: 'Nombre',
      contactNamePlaceholder: 'Tu nombre',
      contactEmailLabel: 'Correo',
      contactEmailPlaceholder: 'tu@ejemplo.com',
      contactTopicLabel: 'Tema',
      contactOptionRecipe: 'Solicitud de receta',
      contactOptionTip: 'Consejo de cocina',
      contactOptionSwap: 'Cambio de ingrediente',
      contactOptionFeedback: 'Comentario general',
      contactMessageLabel: 'Mensaje',
      contactMessagePlaceholder: 'Cuéntanos qué te gustaría cocinar o aprender',
      contactSubmit: 'Enviar mensaje',
      contactInfoTitle: 'Visita la cocina',
      contactInfoEmail: 'Correo: hello@kitchenlo.com',
      contactInfoInspiration: 'Inspiración: actualizaciones diarias de recetas',
      contactInfoResponse: 'Respuesta: normalmente en un día hábil'
    }
  };

  const langButtons = document.querySelectorAll('.lang-option');
  const currentLang = localStorage.getItem('kitchenly-lang') || 'en';

  function applyTranslation(lang) {
    const t = translations[lang] || translations.en;
    document.querySelectorAll('[data-key]').forEach((element) => {
      const key = element.getAttribute('data-key');
      if (key && t[key]) {
        element.textContent = t[key];
      }
    });

    document.querySelectorAll('[data-placeholder-key]').forEach((element) => {
      const key = element.getAttribute('data-placeholder-key');
      if (key && t[key]) {
        element.setAttribute('placeholder', t[key]);
      }
    });

    document.querySelectorAll('[data-aria-key]').forEach((element) => {
      const key = element.getAttribute('data-aria-key');
      if (key && t[key]) {
        element.setAttribute('aria-label', t[key]);
      }
    });

    document.querySelectorAll('[data-alt-key]').forEach((element) => {
      const key = element.getAttribute('data-alt-key');
      if (key && t[key]) {
        element.setAttribute('alt', t[key]);
      }
    });

    const recipeTitleEl = document.getElementById('recipeOfTheDayTitle');
    if (recipeTitleEl && recipeTitleEl.textContent.trim() === 'Loading...' && t.loadingText) {
      recipeTitleEl.textContent = t.loadingText;
    }

    const brandEl = document.querySelector('.brand');
    if (brandEl) {
      brandEl.textContent = 'Kitchenlo';
    }

    langButtons.forEach((button) => {
      const isActive = button.getAttribute('data-lang') === lang;
      button.classList.toggle('active', isActive);
      button.setAttribute('aria-pressed', String(isActive));
    });
  }

  langButtons.forEach((button) => {
    button.addEventListener('click', () => {
      const nextLang = button.getAttribute('data-lang');
      if (!nextLang) return;
      localStorage.setItem('kitchenly-lang', nextLang);
      applyTranslation(nextLang);
    });
  });

  const dailyRecipes = [
    {
      title: 'Golden Herb Pasta',
      text: 'Silky noodles, roasted garlic, and crunchy herbs create a dinner that comes together fast.',
      image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1200&q=80',
      alt: 'A bowl of golden herb pasta with fresh parsley',
      link: 'recipes.html'
    },
    {
      title: 'Citrus Garden Salad',
      text: 'Bright greens, roasted citrus, and creamy feta bring a light yet satisfying lunch to the table.',
      image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',
      alt: 'A fresh citrus salad with herbs and vegetables',
      link: 'recipes.html'
    },
    {
      title: 'Honey Roasted Chicken',
      text: 'A cozy plate with caramelized edges, warm spices, and a glossy glaze that feels homemade.',
      image: 'https://images.unsplash.com/photo-1518492104633-130d0cc84637?auto=format&fit=crop&w=1200&q=80',
      alt: 'Honey roasted chicken served with herbs',
      link: 'recipes.html'
    }
  ];

  const imageEl = document.getElementById('recipeOfTheDayImage');
  const titleEl = document.getElementById('recipeOfTheDayTitle');
  const textEl = document.getElementById('recipeOfTheDayText');
  const linkEl = document.getElementById('recipeOfTheDayLink');

  if (imageEl && titleEl && textEl && linkEl) {
    const today = new Date();
    const dayKey = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;
    const recipeIndex = dayKey.split('').reduce((sum, char) => sum + char.charCodeAt(0), 0) % dailyRecipes.length;
    const recipe = dailyRecipes[recipeIndex];

    imageEl.src = recipe.image;
    imageEl.alt = recipe.alt;
    titleEl.textContent = recipe.title;
    textEl.textContent = recipe.text;
    linkEl.href = recipe.link;
  }

  const root = document.documentElement;
  const themeToggle = document.querySelector('.theme-toggle');
  const savedTheme = localStorage.getItem('kitchenly-theme') || 'dark';
  root.setAttribute('data-theme', savedTheme);
  if (themeToggle) {
    themeToggle.textContent = savedTheme === 'dark' ? '☀︎' : '☾';
  }

  applyTranslation(currentLang);

  if (themeToggle) {
    themeToggle.addEventListener('click', () => {
      const nextTheme = root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
      root.setAttribute('data-theme', nextTheme);
      localStorage.setItem('kitchenly-theme', nextTheme);
      themeToggle.textContent = nextTheme === 'dark' ? '☀︎' : '☾';
    });
  }

  const navToggle = document.querySelector('.nav-toggle');
  const siteNav = document.querySelector('.site-nav');

  if (navToggle && siteNav) {
    navToggle.addEventListener('click', () => {
      const isOpen = siteNav.classList.toggle('open');
      navToggle.setAttribute('aria-expanded', String(isOpen));
    });

    siteNav.querySelectorAll('a').forEach((link) => {
      link.addEventListener('click', () => {
        siteNav.classList.remove('open');
        navToggle.setAttribute('aria-expanded', 'false');
      });
    });
  }

  const form = document.getElementById('contactForm');
  const status = document.querySelector('.form-status');

  if (form && status) {
    form.addEventListener('submit', (event) => {
      event.preventDefault();
      const name = form.elements.namedItem('name')?.value || '';
      status.textContent = `Thanks, ${name || 'there'}! Your message is on the way.`;
      form.reset();
    });
  }
});
